apache/dubbo-go

public/const.go

add const.go

---

jsonrpc/json.go

add json.go

---

examples/dubbo/go-server/profiles/dev/server.yml
registry/zookeeper/zk_client.go

Fix:bug #42

---

registry/zookeeper/registry.go
registry/zookeeper/zk_client.go

Fix bug #42

---

examples/dubbo/go-client/app/client.go
examples/dubbo/go-client/app/user.go
examples/jsonrpc/go-client/app/client.go
examples/jsonrpc/go-client/app/user.go
filter/imp/echo_filter.go
protocol/dubbo/listener.go
protocol/jsonrpc/server.go
protocol/protocolwrapper/protocol_filter_wrapper.go
protocol/support/rpcinvocation.go

complete echo filter and filter invoker chain

Add&Fix:add Echo in example & fix 'no result after filter'

---

protocol/dubbo/pool.go

update created time for connection reuse

update created time

---

README.md
README_CN.md

Change readme
Fixes #
```release-note
```

Fix: change go-for-apache-dubbo to dubbo-go as issue #74

---

protocol/dubbo/pool.go

Modify Chinese notes
No
```release-note
```

Modify Chinese notes

---

common/logger/logger_test.go

Fixes https://github.com/apache/dubbo-go/issues/88.
```release-note
none
```

fix issue88

---

go.mod
go.sum
protocol/dubbo/client_test.go

fix hessian codec error
Fixes #71
None
None

fix issue #71

---

README.md
README_CN.md
config/service_config.go

p2p connect have a bug 
Fixes #
```release-note
```

Fix: for p2p bug

---

protocol/dubbo/readwriter.go
protocol/dubbo/server.go

To Fix Bug: every session has a session map
Fixes #<https://github.com/AlexStocks/getty/issues/18>
```release-note
```

Fix: alexstocks/getty issue 18

---

cluster/loadbalance/least_active.go
config/service_config_test.go
protocol/dubbo/client_test.go
protocol/dubbo/codec.go
protocol/dubbo/dubbo_invoker_test.go
protocol/dubbo/dubbo_protocol_test.go
protocol/dubbo/listener.go
protocol/jsonrpc/server.go

Fix:fix test & some spelling problems

---

registry/zookeeper/registry.go

fix a bug about register after group feature commit.
Fixes #
```release-note
NONE
```

Fix:fix a bug about register after group feature commit

---

config/config_loader_test.go
config/reference_config.go
config/reference_config_test.go
config/registry_config.go
config/service_config.go
config/service_config_test.go
config/testdata/consumer_config.yml
config/testdata/consumer_config_with_configcenter.yml
config/testdata/provider_config.yml
examples/dubbo/go-client/profiles/dev/client.yml
examples/dubbo/go-client/profiles/release/client.yml
examples/dubbo/go-client/profiles/test/client.yml
examples/dubbo/go-server/profiles/dev/server.yml
examples/dubbo/go-server/profiles/release/server.yml
examples/dubbo/go-server/profiles/test/server.yml
examples/jsonrpc/go-client/profiles/dev/client.yml
examples/jsonrpc/go-client/profiles/release/client.yml
examples/jsonrpc/go-client/profiles/test/client.yml
examples/jsonrpc/go-server/profiles/dev/server.yml
examples/jsonrpc/go-server/profiles/release/server.yml
examples/jsonrpc/go-server/profiles/test/server.yml

Add registries config option in referenceConfig & serviceConfig.
Fixes #
```release-note
NONE
```

Add:registries config option in referenceConfig & serviceConfig

---

cluster/router/condition_router.go
cluster/router/condition_router_test.go
go.mod
go.sum

remove gostd package,and import gost
Fixes #
```release-note
```

replace hashset package

---

.gitignore
README.md
README_CN.md
common/rpc_service_test.go
config_center/zookeeper/impl.go
go.mod
go.sum
protocol/dubbo/client_test.go
protocol/jsonrpc/json_test.go
registry/zookeeper/registry.go
registry/zookeeper/registry_test.go

Add:update readme

---

go.mod
go.sum

None
None
None
```release-note
- upgrade getty: remove read queue
```

upgrade getty: remove read queue

---

examples/configcenter/zookeeper/dubbo/with-configcenter-go-client/app/client.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-client/app/user.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-server/app/server.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-server/app/user.go
examples/general/dubbo/go-client/app/client.go
examples/general/dubbo/go-client/app/user.go
examples/general/dubbo/go-server/app/server.go
examples/general/dubbo/go-server/app/user.go
examples/general/dubbo/go-server/app/user_provider.go
examples/general/dubbo/go-server/app/user_provider1.go
examples/general/dubbo/go-server/app/user_provider2.go
examples/helloworld/dubbo/go-client/app/user.go
examples/helloworld/dubbo/go-server/app/user.go
go.mod
go.sum
protocol/dubbo/client.go
protocol/dubbo/client_test.go
protocol/dubbo/codec.go
protocol/dubbo/codec_test.go
protocol/dubbo/listener.go
protocol/dubbo/readwriter.go

fix hessian2 package after transferring to apache

fix hessian2 package after transferring to apache

---

config/reference_config.go

Fixes #
Fix:bug in reference_config
```release-note
```

Fix:bug in reference_config

---

go.sum

Fix:go.mod

---

cluster/cluster_impl/failback_cluster_invoker.go
cluster/cluster_impl/failsafe_cluster_invoker.go

remove ineffassign

---

cluster/cluster_impl/broadcast_cluster.go
cluster/cluster_impl/broadcast_cluster_invoker.go
cluster/cluster_impl/broadcast_cluster_invoker_test.go

add broadcast cluster
NONE
```release-note
```

add broadcast cluster

---

cluster/cluster_impl/base_cluster_invoker.go
config_center/zookeeper/impl.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-client/app/client.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-client/app/user.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-server/app/server.go
examples/configcenter/zookeeper/dubbo/with-configcenter-go-server/app/user.go
examples/configcenter/zookeeper/jsonrpc/with-configcenter-go-client/app/client.go
examples/configcenter/zookeeper/jsonrpc/with-configcenter-go-server/app/server.go
examples/general/dubbo/go-client/app/client.go
examples/general/dubbo/go-client/app/user.go
examples/general/dubbo/go-server/app/server.go
examples/general/dubbo/go-server/app/user.go
examples/general/dubbo/java-client/src/main/java/com/ikurento/user/Consumer.java
examples/general/dubbo/java-server/src/main/java/com/ikurento/user/UserProviderAnotherImpl.java
examples/general/dubbo/java-server/src/main/java/com/ikurento/user/UserProviderImpl.java
examples/general/jsonrpc/go-client/app/client.go
examples/general/jsonrpc/go-server/app/server.go
examples/general/jsonrpc/java-client/src/main/java/com/ikurento/user/Consumer.java
examples/general/jsonrpc/java-server/src/main/java/com/ikurento/user/UserProviderAnotherImpl.java
examples/general/jsonrpc/java-server/src/main/java/com/ikurento/user/UserProviderImpl.java
examples/helloworld/dubbo/go-server/app/server.go
examples/helloworld/dubbo/java-server/src/main/java/com/ikurento/user/UserProviderImpl.java
registry/zookeeper/listener.go
registry/zookeeper/registry.go
remoting/zookeeper/facade.go

Mod: translate Chinese comments to English

---

.travis.yml

Remve zk jar file for unit test, and modify .travis.yml file to download zk jar before execute unit test.
Fixes #
```release-note
```

Rem: zk jar

---

protocol/rpc_status.go

Remove author info & rename file name
Fixes #
```release-note
```

Mod:rm author info & rename file name

---

common/url.go
common/url_test.go

Add:retries mergeUrl
Fixes #
```release-note
```

Add:retries mergeUrl

---

protocol/dubbo/client.go
protocol/dubbo/server.go

fix issue:204

---

registry/protocol/protocol.go

Fix: registryProtocol.Export

---

registry/directory/directory.go

If annotate these codes, a more serious problem will occur. Customer will get the offline provider IP. So need to add the following code
Fixes #
```release-note
```

Add: deal res.Action in refreshInvokers

---

README.md
README_CN.md

Update README.md README_CN.md

---

README.md
README_CN.md

Update the README.md about AccessLogFilter
Fixes #
```release-note
```

Doc: Update README.md about AccessLogFilter

---

README.md
README_CN.md
before_ut.bat

Add before_ut.bat for windows user
```release-note
```

Add before_ut.bat for windows user

---

README.md

update user list

---

README.md

add user list logo

---

README.md
README_CN.md

Fix the issue that the link of contribution is 404
Fixes #
```release-note
```

Doc: change the link of contribution-info

---

examples/helloworld/dubbo/go-client/assembly/windows/dev.sh

Update dev.sh fix GOOS variable
Fixes #
```release-note
```

Update dev.sh fix GOOS variable

---

README.md
README_CN.md

Doc: Modify README.md and README_CN.md for TpsLimitFilter

---

protocol/dubbo/client.go

Fix: group

---

registry/protocol/protocol.go
registry/protocol/protocol_test.go
registry/zookeeper/listener.go

After fixing the registryProtocol singleton issue, #252 was found. And this PR will fix this. 
Please take a serious look at this PR.
Fixes #252 
```release-note
```

Fix: negative wait group count

---

protocol/dubbo/client.go

增强client的代码
NONE
NONE
```release-note
```

feat(dubbo/client): 增强client的代码

---

protocol/dubbo/dubbo_invoker.go

advance the destroy impl of dubboInvoker
NONE
```release-note
```

feat(dubbo/invoker): 修改dubbo 关闭的方式

---

filter/impl/generic_filter.go

Develop generic code fix

---

README.md

Adding GenericServiceFilter in README
Fixes #
```release-note
```

Adding GenericServiceFilter in README

---

metrics/impl/default_compass.go
metrics/impl/default_compass_test.go
metrics/metered.go

Implementing the Metered interface, so we can collect the exponentially-weighted moving average rates.
Fixes #
```release-note
```

Implementing Metered interface

---

LICENSE
NOTICE

Mod: License and Notice

---

go.mod
go.sum
registry/etcdv3/listener_test.go
registry/etcdv3/registry.go
registry/kubernetes/listener.go
registry/kubernetes/listener_test.go
registry/kubernetes/registry.go
registry/kubernetes/registry_test.go
remoting/etcdv3/client_test.go
remoting/etcdv3/listener.go
remoting/kubernetes/client.go
remoting/kubernetes/facade.go
remoting/kubernetes/listener.go
remoting/kubernetes/listener_test.go
remoting/kubernetes/store.go
remoting/kubernetes/store_test.go

Ftr: kubernetes for registry
Fixes #
temporary lack of unit testing
```release-note
```

[WIP] kubernetes as registry

---

protocol/dubbo/client.go
protocol/dubbo/config.go
protocol/dubbo/listener.go
protocol/dubbo/pool.go

reduce protocol/dubbo/pool.go lock scope

Imp: reduce protocol/dubbo/pool.go lock scope

---

common/url_test.go
filter/filter_impl/auth/consumer_sign_test.go
filter/filter_impl/auth/default_authenticator_test.go
filter/filter_impl/auth/provider_auth_test.go
filter/filter_impl/metrics_filter_test.go
metrics/prometheus/reporter_test.go

Fix: Test case

---

protocol/rest/rest_config_initializer.go
protocol/rest/rest_config_initializer_test.go
protocol/rest/rest_interface/rest_config.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol.go
protocol/rest/rest_protocol_test.go
protocol/rest/rest_server/go_restful_server.go

Fix rest protocol issue

---

README.md

add [![go.dev reference](https://img.shields.io/badge/go.dev-reference-007d9c?logo=go&logoColor=white&style=flat-square)](https://pkg.go.dev/github.com/apache/dubbo-go?tab=doc) icon
Fixes #
```release-note
```

Update README.md add godev

---

config_center/nacos/client_test.go

fix:nacos client_test bug

---

config_center/nacos/client.go
config_center/nacos/client_test.go
config_center/nacos/impl_test.go
filter/access_key.go
filter/authenticator.go
filter/filter_impl/auth/accesskey_storage.go
filter/filter_impl/auth/accesskey_storage_test.go
filter/filter_impl/auth/consumer_sign.go
filter/filter_impl/auth/consumer_sign_test.go
filter/filter_impl/auth/default_authenticator.go
filter/filter_impl/auth/default_authenticator_test.go
filter/filter_impl/auth/provider_auth.go
filter/filter_impl/auth/provider_auth_test.go
filter/filter_impl/auth/sign_util.go
filter/filter_impl/auth/sign_util_test.go

* Format import
* Add apache license
Fixes #
```release-note
```

Fix : Format import and add apache license

---

common/proxy/proxy.go
protocol/dubbo/dubbo_invoker.go
protocol/dubbo/pool.go
registry/directory/directory.go
registry/zookeeper/listener.go
remoting/zookeeper/client.go
remoting/zookeeper/listener.go

Optimized logs，Easy to troubleshoot
Fixes #
```release-note
```

change log

---

README.md
README_CN.md

modify readme

---

go.mod
metrics/histogram.go
metrics/impl/default_metric_manager.go
metrics/impl/histogram_impl.go
monitor/collector/collector.go
monitor/dubbogo_exporter.go

Prometheus for dubbogo first step, more metrics collect please stay tuned
1. Compass metrics collect summary implement
Fixes #
```release-note
```

[WIP] dubbogo compass metrics Prometheus support

---

config/base_config.go
config/base_config_test.go
config/condition_router_config.go
config/consumer_config.go
config/provider_config.go

* Extract common method for load config file
Fixes #
```release-note
```

Add: optimize load config file

---

before_ut.bat
before_ut.sh

if zkJar not exist,it will download it.

---

protocol/rest/rest_config_initializer.go
protocol/rest/rest_config_initializer_test.go
protocol/rest/rest_config_reader/testdata/consumer_config.yml
protocol/rest/rest_config_reader/testdata/provider_config.yml
protocol/rest/rest_interface/rest_config.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol.go
protocol/rest/rest_protocol_test.go

Fix Rest Protocol

---

before_ut.bat

Fix: problem in before_ut.bat

---

README.md
README_CN.md

Change README

---

CHANGE.md
README.md
README_CN.md

Mod: readme.md & change.md

---

.travis.yml
common/constant/key.go
config/reference_config.go
config/service_config.go
registry/base_registry.go
registry/etcdv3/registry_test.go
registry/zookeeper/registry_test.go

Enhance url init code, some url's parameters init should move into getUrlMap func.
Fixes #
```release-note
```

Mod:enhance url init code

---

common/constant/key.go
config/reference_config.go
config/service_config.go

Mod:release key

---

config_center/apollo/impl.go
config_center/dynamic_configuration.go
config_center/mock_dynamic_config.go
config_center/nacos/impl.go
config_center/nacos/impl_test.go
config_center/nacos/listener.go
config_center/zookeeper/impl.go
config_center/zookeeper/impl_test.go
remoting/zookeeper/client.go

Fixes #428 
```release-note
```

Publish config

---

common/rpc_service.go
common/rpc_service_test.go
config/config_loader.go
config/config_loader_test.go
config/service_config.go
filter/filter_impl/generic_service_filter_test.go
protocol/dubbo/client_test.go
protocol/dubbo/dubbo_exporter.go
protocol/grpc/grpc_exporter.go
protocol/jsonrpc/http_test.go
protocol/jsonrpc/jsonrpc_exporter.go
protocol/jsonrpc/jsonrpc_invoker_test.go
protocol/rest/rest_exporter.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol_test.go

Add: GetInterface for rpc_service.go

---

registry/etcdv3/registry.go
registry/kubernetes/registry.go
registry/zookeeper/registry.go

Consumer can not subscribe service in registry
Fixes #
```release-note
```

Fix: bug of subscribe

---

config/reference_config.go
config/service_config.go

Test successful as follow:
Fixes #
```release-note
```

Fix: remove category key

---

common/extension/registry_directory.go
registry/directory/directory.go
registry/directory/directory_test.go
registry/protocol/protocol.go

registry directory extension, the 
Fixes #
```release-note
```

Add:registry directory extension

---

common/observer/dispatcher/mock_event_dispatcher.go
go.mod
go.sum
registry/nacos/service_discovery.go
registry/nacos/service_discovery_test.go

Last time when I implement the NacosServiceDiscovery, the DispatchEvent method is marked as TODO.
Now I do implement this.

Implement event dispatch method

---

common/constant/key.go
registry/protocol/protocol.go
registry/protocol/protocol_test.go

filter registry url params starting with dot.

filter registry url params starting with dot

---

.travis.yml
integrate_test.sh
test/integrate/dubbo/go-client/Dockerfile
test/integrate/dubbo/go-server/Dockerfile
test/integrate/dubbo/go-server/server.yml

The previous PR https://github.com/apache/dubbo-go/pull/520
had some scenarios that were not considered, which led to errors in integration testing when the PR was merged into the local branch.
Fixes #
```release-note
```

Fix docker ci bug

---

common/url.go

optmize url to string
Fixes #
```release-note
```

Opt: optimize url to string

---

cluster/cluster_impl/available_cluster_invoker_test.go
cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/failover_cluster_test.go
cluster/directory/base_directory.go
cluster/directory/base_directory_test.go
cluster/directory/static_directory.go
config/base_config_test.go
config/consumer_config.go
config/service_config.go
filter/filter_impl/hystrix_filter.go
filter/filter_impl/token_filter_test.go
protocol/dubbo/listener.go
protocol/dubbo/pool.go
protocol/jsonrpc/http.go
protocol/jsonrpc/json.go
protocol/jsonrpc/jsonrpc_protocol.go
protocol/jsonrpc/server.go
registry/consul/listener.go
registry/kubernetes/listener_test.go
registry/kubernetes/registry_test.go
registry/nacos/registry_test.go
remoting/zookeeper/client.go
remoting/zookeeper/listener.go

fix [gitee_scans](https://gitee.com/dubbogo/dubbo-go/gitee_scans/report?task_id=723471) shadow error
Fixes #514

Fix: gitee code analysis shadow err

---

registry/zookeeper/registry_test.go

* `Test_UnSubscribe` should call `UnSubscribe`, not `DoUnSubscribe`
Fixes #
```release-note
```

Rft: Change test case method

---

common/constant/key.go
common/url.go
config_center/nacos/client.go
config_center/nacos/listener.go
go.mod
go.sum
registry/nacos/registry.go

**What this PR does:**
1. update nacos-sdk-go version to v0.3.2, this version fix some bug;
2. optimized nacos config  code

Update Nacos SDK version

---

README.md
README_CN.md

add mosn logo

---

README.md
README_CN.md

Mod: update haozhuo logo url

---

protocol/dubbo/pool.go

remove unuseful codes
Fixes #
```release-note
```

Mod: remove unuseful codes

---

.gitignore

- adds vim temporary files to .gitignore
Fixes #
- None
```release-note
```

Mod: ignore vim temporary files

---

protocol/dubbo/dubbo_invoker.go

之前项目在review后，优化了下代码，发现优化的代码有问题，重新调整下代码。
path不在url的param中，而是通过url.Path获取

fix issue for network refactor

---

README.md
README_CN.md

Mod: Update links in readme

---

protocol/dubbo/client_test.go
protocol/dubbo/codec_test.go
protocol/dubbo/dubbo_invoker_test.go
protocol/dubbo/dubbo_protocol_test.go
protocol/grpc/common_test.go
protocol/grpc/grpc_invoker_test.go
protocol/grpc/grpc_protocol_test.go
protocol/jsonrpc/http_test.go
protocol/jsonrpc/json.go
protocol/jsonrpc/json_test.go
protocol/jsonrpc/jsonrpc_invoker_test.go
protocol/jsonrpc/jsonrpc_protocol_test.go
protocol/protocolwrapper/mock_protocol_filter.go
protocol/protocolwrapper/protocol_filter_wrapper_test.go
protocol/rest/client/client_impl/resty_client.go
protocol/rest/config/reader/rest_config_reader_test.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol_test.go
protocol/rpc_status.go
protocol/rpc_status_test.go

Mod: code linter warnings

---

common/constant/key.go
registry/nacos/base_registry.go

Add: namespaceId config for nacos

---

registry/zookeeper/listener.go
registry/zookeeper/registry.go
remoting/zookeeper/listener.go

Fix: waitGroup use

---

common/rpc_service.go
remoting/zookeeper/listener.go

Develop fix zk no provider bug

---

go.mod
go.sum

Upgrade hession version

---

config/router_config.go
config/router_config_test.go

* Fix condition router bug: `gost.Hashset` must add pointer for key.
* Revert test case 
Fixes #
```release-note
```

Fix: condition router bug and revert test case

---

config/consumer_config.go
config/provider_config.go

**What this PR does**:  when does not set registries, it will be nil , when config.Load(), it will be panic
Fixes #
```release-note
```

Fix: panic when checkRegistries

---

config/graceful_shutdown_signal_darwin.go
config/graceful_shutdown_signal_linux.go
config/graceful_shutdown_signal_windows.go
registry/nacos/registry.go
registry/protocol/protocol.go

fix not inovke nacos destroy when graceful shutdown

fix not inovke nacos destroy when graceful shutdown

---

README_CN.md

Mod: 用词错误，忝列的意思是有愧于排列其中，应该是添加或者添列。

---

common/logger/log.yml
go.mod
go.sum
registry/nacos/service_discovery_test.go
test/integrate/dubbo/go-client/log.yml
test/integrate/dubbo/go-server/log.yml

- fix https://github.com/apache/dubbo-go/issues/682
- change log stack level from warn to error
- None
```release-note
NONE
```

stack level

---

protocol/dubbo/dubbo_protocol_test.go

fix TestDubboProtocol_Export test 
Fixes #
```release-note
```

fix: TestDubboProtocol_Export test

---

cluster/router/tag/router_rule.go
cluster/router/tag/tag_router.go
common/logger/logger.go
config/ssl_config.go
config_center/nacos/facade.go
go.mod
go.sum
protocol/dubbo/client.go
protocol/dubbo/listener.go
protocol/dubbo/pool.go
protocol/dubbo/readwriter.go
protocol/dubbo/server.go
registry/etcdv3/listener_test.go
registry/kubernetes/registry.go
registry/nacos/listener.go
remoting/etcdv3/facade.go
remoting/zookeeper/facade.go
remoting/zookeeper/listener.go
test/integrate/dubbo/go-server/server.go

fix deep copy
Fixes #
```release-note
```

Fix: fix tag router rule copy

---

integrate_test.sh
test/integrate/dubbo/go-client/Dockerfile
test/integrate/dubbo/go-client/go.mod
test/integrate/dubbo/go-server/Dockerfile
test/integrate/dubbo/go-server/go.mod

Revert "Fix: integration testing problems"

---

protocol/dubbo/dubbo_codec.go
protocol/dubbo/impl/codec_test.go
protocol/dubbo/impl/hessian.go
protocol/dubbo/impl/request.go
protocol/dubbo/impl/response.go
remoting/getty/dubbo_codec_for_test.go
remoting/getty/listener_test.go
remoting/getty/opentracing.go

fix: resove dev RPCResult struct change

---

protocol/dubbo/dubbo_protocol.go
protocol/jsonrpc/jsonrpc_invoker.go
remoting/getty/getty_server.go

1.  delete dubbo_protocol assert remoting.ExchangeClient
2. add some comment
Fixes #
```release-note
```

feat: delete dubbo_protocol assert remoting.ExchangeClient

---

remoting/getty/listener.go
remoting/getty/readwriter.go
test/integrate/dubbo/go-client/go.mod
test/integrate/dubbo/go-server/go.mod

update the comment of getty/listener.go 
Fixes #
```release-note
```

feat: update the comment of getty/listener

---

README.md
README_CN.md

* Add history release to `README.md` and `README_CN.md`
Fixes #
```release-note
```

Rft:Add history release to README.md

---

metadata/service/exporter/configurable/exporter.go
metadata/service/exporter/configurable/exporter_test.go
metadata/service/exporter/exporter.go
registry/servicediscovery/service_discovery_registry.go

Fixes #
https://github.com/apache/dubbo-go/issues/774
```release-note
```

Fix:  issue 774 [fix metadata default port]

---

remoting/getty/pool.go
remoting/getty/pool_test.go

Fix: go client quit abnormally when it connects java server

---

registry/etcdv3/registry.go
registry/etcdv3/service_discovery.go

issue #827
Fixes #
ectd注册中心BUG
```release-note
```

Fix: etcd registry

---

go.mod
go.sum

change zk version to v1.0.2

---

filter/filter_impl/generic_filter.go
filter/filter_impl/generic_filter_test.go
go.mod
go.sum
metadata/service/exporter/configurable/exporter.go
metadata/service/exporter/configurable/exporter_test.go
metadata/service/exporter/exporter.go
registry/base_registry.go
registry/consul/registry.go
registry/consul/registry_test.go
registry/consul/utils_test.go
registry/etcdv3/registry.go
registry/etcdv3/service_discovery.go
registry/servicediscovery/service_discovery_registry.go
remoting/etcdv3/facade.go
remoting/getty/pool.go
remoting/getty/pool_test.go

Fix: For release bug fix version - v1.5.4

---

CHANGE.md
README.md
README_CN.md

Ftr: Add release notes for v1.5.4

---

cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/failover_cluster_invoker.go

1.when there is no invoker is available, we should return "No Provider Available" Error.
2.Add some log

Fix : when there is no invoker is available, we should return "No Provider Available" Error.

---

cluster/router/chain/chain.go

bug: the ticket just need to create once

---

remoting/zookeeper/listener.go

fix bug: pathMap cache need to delete after node removed

---

README.md
README_CN.md

**What this PR does**: add tashequ to user list
Fixes #
```release-note
```

Mod: add tashequ to user list

---

cluster/cluster_impl/forking_cluster_invoker.go
cluster/loadbalance/consistent_hash.go
cluster/router/healthcheck/default_health_check.go
common/url.go
common/url_test.go

it is just a warning about [CWE-681](https://github.com/github/codeql-go/blob/main/ql/src/Security/CWE-681/IncorrectIntegerConversion.ql)
Fixes #839
```release-note
None
```

Fix Warnings: incorrect conversion between integer type #857

---

CHANGE.md
README.md
README_CN.md

* Add release notes for v1.4.5
Fixes #
```release-note
```

Ftr: Add release notes

---

README.md
README_CN.md

Add: 跟谁学 logo pr

---

README.md
README_CN.md

**What this PR does**: just add logo pr

Add: huowu com logo

---

protocol/rest/server/server_impl/go_restful_server.go

Remove useless code in go_restful_server.go

Remove useless code in go_restful_server.go

---

README.md
README_CN.md

你好，我们公司正在使用dubbo-go, 目前使用的版本是1.5.0.

Add icsoc icon

---

.github/dependabot.yml

* Change target-branch and schedule interval of Dependabot
Fixes #
```release-note
```

Imp:Change target-branch and schedule interval of Dependabot

---

README.md
README_CN.md

What this PR does:
add MGTV LOGO to the readme user list
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:

add MGTV LOGO to the readme user list

---

common/proxy/proxy.go
config/reference_config.go

Add GetInvoker method in Proxy.

Add GetInvoker method in Proxy.

---

common/url.go

parameter
Introduce a new method 'DelParam' on common.URL so that now it is possible to remove one particular parameter from the URL.
Fixes #
```release-note
```

DelParam method on common.URL

---

protocol/invocation.go
protocol/invocation/rpcinvocation.go

Add ParameterTypeNames at Invocation.

Feature: Add ParameterTypeNames at Invocation 

---

filter/filter_impl/tracing_filter.go

fix the wrong judgment in rpc result error
Fixes #
```release-note
```

Fix: fix the wrong judgment in rpc result error

---

.travis.yml
CHANGE.md
cluster/router/healthcheck/default_health_check.go
common/url.go
protocol/dubbo/impl/hessian.go
registry/zookeeper/registry.go

* I will release 1.5.5 base on 1.5.5-rc1 and exclude #914
* add two PR as below
- [Fix: URL.String() data race panic](https://github.com/apache/dubbo-go/pull/944)
- [Fix: generic "encode hessian.Object"](https://github.com/apache/dubbo-go/pull/945)
Fixes #
```release-note
```

[Ftr]:Ready for release 1.5.5 but exclude #914

---

remoting/kubernetes/registry_controller.go

[issue-813](https://github.com/apache/dubbo-go/issues/813) fix, and the docker-image **registry.cn-hangzhou.aliyuncs.com/scottwang/dubbogo-client** and **registry.cn-hangzhou.aliyuncs.com/scottwang/dubbogo-server** have been updated, and user can use the [Guide](https://github.com/apache/dubbo-go-samples/tree/master/registry/kubernetes)  to verify. 
Fixes #813
```release-note
```

Fix: bug in issue 813 and update docker image

---

registry/nacos/registry.go

Use nacos constant instead of hardcoded string in nacos registry.
Fixes #
```release-note
```

Ftr: Use nacos constant instead of hardcoded string in nacos registry

---

README.md
README_CN.md

你好，我们公司正在使用dubbo-go, 目前使用在MOSN中的服务注册方面.

Add dmall icon

---

README.md
README_CN.md

Fixes #1042 
```release-note
```

Replace ci icon

---

protocol/rest/config/reader/rest_config_reader.go
protocol/rest/config/rest_config.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol.go

Because of #914 , we need another url param which is the id of config to bind rest config and other config.

Fix can't run rest protocol sample

---

README.md
README_CN.md

Fixes #
```release-note
NONE
```

docs: fix grammar and fix links

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGE.md
README.md
README_CN.md
cluster/router/condition/app_router_test.go
config/testdata/router_config.yml
config/testdata/router_config_error.yml
contributing.md
doc/apache/apache-release-procedure-20200306.md
remoting/consul/test_agent.go

Fixes #
```release-note
NONE
```

Rft: remove trailing whitespace

---

cluster/router/local/factory.go
config/graceful_shutdown_config_test.go

change from develop to 1.5 caused this small problem, this pr fixed it.
Fixes #
```release-note
```

fix: fix bugs caused by 1.5

---

common/constant/version.go

Update dubbogo version to 1.5.6.
Fixes #
```release-note
```

Ftr: up 1.5.6 version

---

protocol/dubbo/impl/hessian.go

Give it an initial value when attachments is nil
Fixes https://github.com/apache/dubbo-go/issues/993
```release-note
```

Bugfix: nil attachments

---

.gitmodules
registry/nacos/listener.go
registry/nacos/service_discovery_test.go

* refer to dubbo-go-samples 1.5.6-rc2
Fixes #
```release-note
```

Ftr: add samples as submodule into dubbo-go

---

CHANGE.md

Add 1.5.6-rc2 to changelist
Fixes #
```release-note
```

[Ftr] up 1.5.6 changelist

---

remoting/nacos/builder.go

nacos for service_discovery support namespace

---

test/integrate/dubbo/go-client/go.mod
test/integrate/dubbo/go-server/go.mod

fix: fix test file gomod

---

cluster/cluster_impl/failback_cluster_invoker.go
go.sum

Fixes #1178 
```release-note
```

Fix: get failback error

---

registry/nacos/service_discovery_test.go

- fix 1.5 ut
```release-note
NONE
```

fix 1.5 ut

---

CHANGE.md

update: 1.5 change log

---

metadata/report/zookeeper/report_test.go

As the name implied, unit tests for app metadata reporter of zookeeper are added.
Fixes #
```release-note
NONE
```

Tst: Add unit tests for app metadata reporter of zookeeper

---

go.mod
go.sum

* 解决`m1`芯片运行异常： https://github.com/shirou/gopsutil/issues/1000
Fixes #
```release-note
```

fix:support m1

---

common/logger/logger.go
config/base_config.go
config/base_config_test.go
config/config_api.go
config/config_center_config.go
config/config_loader.go
config/config_loader_options.go
config/config_loader_test.go
config/consumer_config.go
config/graceful_shutdown_test.go
config/metadata_report_config_test.go
config/provider_config.go
config/reference_config.go
config/registry_config.go
config/service_config.go
config/service_config_test.go
metadata/service/exporter/configurable/exporter.go

- fix type and remove useless code
NONE
```release-note
NONE
```

fix type; remove useless code

---

config_center/nacos/impl.go
go.mod
go.sum

update gost version

---

cluster/loadbalance/consistent_hash_test.go

fix: loadbalance unit test

---

config/config_loader.go

I don't need a default value when I have only configured Registry.

registrys default

---

.github/workflows/github-actions.yml
integrate_test.sh
test/integrate/dubbo/go-server/Dockerfile

Adding integration tests using dubbo-go-samples
Fixes #
```release-note
NONE
```

Ftr: Adding integration tests using dubbo-go-samples

---

config/config_loader.go

- fix a bug that URL isn't registered as a POJO(see also #1238)
Fixes #
```release-note
NONE
```

Fix: URL serialization bug

---

metadata/identifier/base_metadata_identifier.go
metadata/identifier/base_metadata_identifier_test.go
metadata/identifier/metadata_identifier_test.go
metadata/identifier/service_metadata_identifier_test.go

Fix the issue mentioned in #1288 for dubbo-go v3.0
Fixes #1288 
```release-note
```

[#1288] fix the inconsistent filepath key logic for v3.0

---

.github/PULL_REQUEST_TEMPLATE.md

Fix Pull Request Template url error.

Fix: Pull Request Template url error.

---

protocol/dubbo/dubbo_invoker.go

这个pr是小米同学复制到了1.5分支：https://github.com/apache/dubbo-go/pull/1336
Fixes #
```release-note
```

fix:generic method timeout

---

.gitignore
registry/zookeeper/registry.go

fix: mock zk registry

---

config/root_config.go

up:router slice

---

config/root_config.go

add license

---

registry/nacos/registry_test.go

Fix: Fixed nacos unit test runs incorrectly in some cases

---

registry/nacos/registry.go

Fixes #1331
```release-note
None
```

Ftr: Change ServiceName like Java Style on Nacos for 1.5

---

config/protocol_config.go
config/provider_config.go
imports/imports.go
protocol/grpc/client.go
protocol/jsonrpc/jsonrpc_protocol.go
protocol/rest/rest_protocol.go

1. Add imports package
2. remote default protocol ip.
Fixes #
```release-note
```

fix: prepare to refactor samples

---

common/rpc_service.go
config/config_api.go

fix: pb stub function bug

---

config/reference_config.go
config/registry_config.go
config/root_config.go
registry/protocol/protocol.go

fix: support no registry

---

config/protocol_config.go
config/provider_config.go
remoting/getty/config.go
remoting/getty/getty_client.go
remoting/getty/getty_server.go
remoting/getty/pool.go

feat(config): add new protocol config

---

config/logger_config.go
go.mod
go.sum
metadata/service/exporter/configurable/exporter.go
protocol/dubbo3/dubbo3_invoker.go
protocol/dubbo3/dubbo3_invoker_test.go
protocol/dubbo3/dubbo3_protocol.go
protocol/dubbo3/dubbo3_protocol_test.go
protocol/dubbo3/internal/client.go
protocol/dubbo3/internal/helloworld.pb.go
protocol/dubbo3/internal/server.go
protocol/jsonrpc/http_test.go

Add triple attachment

---

registry/kubernetes/registry_test.go

fix: remove k8s ut to enhance stablility of ci

---

common/proxy/proxy.go
config/generic/generic_service.go

- Align generic invocation interface with Java.
- Optimize logging information.
Fixes #
The corresponding PR for dubbo-go-samples(https://github.com/apache/dubbo-go-samples/pull/248) is created, but this PR should be merged before the dubbo-go-samples is merged. 
```release-note
NONE
```

Ftr: Align generic invocation interface with Java

---

.gitignore
CHANGE.md

up change log

---

filter/echo/filter.go
filter/seata/filter.go

#1458 delete useless log

---

config/config_loader.go
registry/etcdv3/service_discovery.go
registry/file/service_discovery.go
registry/nacos/service_discovery.go

Feat: config enhance (service discovery)

---

.github/workflows/github-actions.yml
.gitignore
metadata/report/nacos/cache/config/com.test.MyTest:1.0.0:test_group:service:nacos:revisiona@@test_group@@

fix: remove old integrate test

---

config/config_loader_options.go
config/config_resolver.go
config/parsers/properties/properties.go
config/service_config.go

add application registry

---

common/constant/key.go
common/url.go
common/url_test.go
protocol/invocation/rpcinvocation.go

Reference Solutions: [https://github.com/apache/dubbo/pull/5950](https://github.com/apache/dubbo/pull/5950)
Fixes #1442
```release-note
None
```

Ftr: compatible with lower versions registering "default." keys

---

cluster/cluster/base/cluster_invoker.go
cluster/cluster_impl/import.go
filter/filter_impl/import.go

Imp: delete useless codes

---

cluster/router/v3router/judger/attachment_match_judger.go
cluster/router/v3router/judger/bool_match_judger.go
cluster/router/v3router/judger/double_match_judger.go
cluster/router/v3router/judger/double_range_match_judger.go
cluster/router/v3router/judger/list_double_match_judger.go
cluster/router/v3router/judger/list_string_match_judger.go
cluster/router/v3router/judger/method_match_judger.go
cluster/router/v3router/judger/string_match_judger.go
cluster/router/v3router/uniform_rule.go

fix #1276: using short receiver name

---

registry/nacos/listener.go
registry/nacos/registry.go

nacos support UnRegister and  UnSubscribe
Fixes #
```release-note
```

nacos support UnRegister and  UnSubscribe

---

config/service_config.go

fix a logic bug

---

config/service_config.go

Revert "fix a logic bug"

---

common/file/suffix.go
config/config_loader_options.go
config/config_loader_options_test.go
config/config_resolver.go

解决数组越界问题感谢 @PhilYue 的指正
Fixes #
* array index out of boundary error
* deprecated `WithGenre` replaced by `WithSuffix`
```release-note
```

FIX:Array boundary problem

---

README.md
README_CN.md

add dubbo-go ecosystem in readme

add Readme ecosystem

---

go.mod
go.sum

update copier version 0.3.4->0.3.2
Fixes https://github.com/apache/dubbo-go/issues/1646
```release-note
```

update copier version 0.3.2

---

common/url.go

support multi address

---

common/url.go

fix: location trim space (#1306)

---

cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/failfast_cluster_invoker.go
cluster/cluster_impl/failover_cluster_invoker.go
cluster/cluster_impl/forking_cluster_invoker.go
cluster/cluster_impl/zone_aware_cluster_invoker.go
common/constant/default.go
filter/filter_impl/generic_filter.go
protocol/invocation.go
protocol/invocation/rpcinvocation.go

support $invokeAsync

---

config/reference_config.go

fix: revert https://github.com/apache/dubbo-go/pull/1700

---

README.md
README_CN.md

add introduction to the dubbo-go command line tool

Ftr: add tools introduce in readme for 3.0

---

go.mod
go.sum
registry/nacos/listener.go

An instance of a subscribed service in Dubbo-Go is currently offline, and Dubbo-Go will initiate an update event, which is not expected
expect: instance offline to initiate a delete event
Fixes #

nacos listener check healthy

---

config/graceful_shutdown_config.go

format imports 3.0

---

config/config_center_config.go
config/config_utils.go
config/config_utils_test.go
config/metadata_report_config.go
config/registry_config.go
config/remote_config.go

refine :https://github.com/apache/dubbo-go/pull/1633
Fixes #

refine client name id

---

README.md
README_CN.md

feat: Update Intellij Plugin Description

---

cluster/router/chain/chain.go
cluster/router/router.go
cluster/router/tag/factory.go
cluster/router/tag/match.go
cluster/router/tag/router.go
cluster/router/tag/router_test.go
cluster/router/v3router/router_chain.go
cluster/router/v3router/uniform_route.go
common/constant/key.go
config/router_config.go
config/router_config_test.go
imports/imports.go

support tag router
dubbo tag router:https://dubbo.apache.org/zh/docs/advanced/routing-rule/
not support runtime: https://github.com/apache/dubbo/issues/9713
conditional route will then submit another PR
Fixes #

tag router

---

README.md
README_CN.md

add ZongHeng logo to user list

---

metrics/prometheus/reporter.go

Signed-off-by: jyz0309 <45495947@qq.com>
Clean the repeated import

Clean code

---

metrics/prometheus/reporter.go

Revert "Clean code"

---

.github/workflows/github-actions.yml
CHANGE.md
common/constant/version.go
config/reference_config.go
go.mod
go.sum

Modifying the CI Process

---

CHANGELOG.md

3.0.2 change log

---

.asf.yaml

Disable merge button for PRs

---

CHANGELOG.md

3.0.3 change log

---

registry/protocol/protocol.go

Start a new routine when subscribing

---

cluster/router/tag/match.go
cluster/router/tag/router.go
cluster/router/tag/router_test.go
config/logger_config.go
config/provider_config.go
config/router_config.go
config/tracing_config.go
config/tracing_config_test.go
protocol/dubbo3/dubbo3_invoker.go
protocol/dubbo3/dubbo3_protocol.go

This is a complementary PR to the previous PR #2336

fix: solve config bool field zero value bug by using pointer

---

CHANGELOG.md

The CHANGLOG was updated to contain features, bugfixes and enhancements
of release v3.1.0.
Signed-off-by: Xuewei Niu <justxuewei@apache.org>

docs: Update CHANGELOG for release v3.1.0

---

common/url.go
config/registry_config_test.go

fix registry primitiveURL

---

client/client.go
client/options.go
cluster/cluster/failback/cluster_invoker.go
protocol/dubbo/dubbo_invoker.go
protocol/invocation/rpcinvocation.go

fixes #2448, put CallOptions into invocation attachments

fixes #2448, put CallOptions into invocation attachments

---

client/options.go
graceful_shutdown/options.go
protocol/triple/internal/server/cmd_server/main.go
protocol/triple/internal/server/cmd_server_with_registry/main.go
server/options.go

See comments in https://github.com/apache/dubbo-go/pull/2449

feat: update API for unification

---

protocol/triple/server.go
protocol/triple/triple.go
server/server.go

1.add triple RefreshService
2.move export service to server.Serve()
related issue #2477

feat:sort triple logic

---

protocol/triple/server.go

fix multiple registrations

---

client/client.go
dubbo.go
loader.go
protocol/triple/internal/client/cmd_with_yml/cmd/main.go
protocol/triple/internal/client/cmd_with_yml/conf/dubbogo.yml
protocol/triple/internal/proto/triple_gen/greettriple/greet.triple.go
protocol/triple/internal/server/cmd_with_yml/cmd/main.go
protocol/triple/internal/server/cmd_with_yml/conf/dubbogo.yml
server/options.go
server/server.go

1.Support dubbo.load()
2.Adjust the stub's code generation logic
related issue https://github.com/apache/dubbo-go/issues/2476 https://github.com/apache/dubbo-go/issues/2493

feat:support dubbo.load()

---

CHANGELOG.md

The CHANGLOG was updated to contain features, bugfixes and enhancements of release v3.1.1-rc1.

docs: Update CHANGELOG for release v3.1.1-rc1

---

metrics/prometheus/registry.go
metrics/prometheus/registry_test.go

fix metrics path not work 

---

protocol/dubbo/dubbo_invoker.go
protocol/dubbo3/dubbo3_invoker.go

fix bug #2546, change timeout of DubboInvoker from Milliseconds to Nanoseconds

fix bug #2546

---

cmd/protoc-gen-go-triple/gen/generator/genTriple.go
cmd/protoc-gen-go-triple/gen/generator/tripleTpl.go
cmd/protoc-gen-go-triple/util/strings.go

Now protoc-gen-go-triple will ignore the case issue and convert to uppercase

Fix:modify uppercase and lowercase issues

---

internal/internal.go
internal/reflection/api.go
protocol/triple/health/healthServer.go
protocol/triple/reflection/serverreflection.go
protocol/triple/server.go
protocol/triple/triple.go

feat:Solving Circular Dependency in Dubbo-Go

---

cluster/loadbalance/loadbalance_benchmarks_test.go

chores: fix misspell

---

client/client.go
client/options.go

fix: client metrics and tracing can't enable

---

metrics/options.go

Fix Prometheus Pushgateway can not enable

Fix Prometheus Pushgateway can not enable

---

logger/zap/zap.go

fix: slice is not used...causing format bug.

---

cluster/router/condition/dynamic_router.go

Increase the priority of traffic-disable option in `condition` sorting.

patch: update sort-func in generating condition-ruleV3.1

---

cluster/router/affinity/factory.go
cluster/router/affinity/route.go
cluster/router/affinity/router.go
cluster/router/affinity/router_test.go
cluster/router/condition/dynamic_router.go
cluster/router/condition/route.go
cluster/router/condition/router_test.go
common/constant/key.go
config/router_config.go

the updated condition-route like 
```yml
configVersion: v3.1
scope: service
key: org.apache.dubbo.samples.CommentService
force: false
runtime: true
enabled: true
#######
conditions:
- from:
match: tag=tag1     # disable traffic
- from:
match: tag=gray
to:
- match: tag!=gray
weight: 100
- match: tag=gray
weight: 900
- from:
match: version=v1
to:
- match: version=v1
```
```yaml
configVersion: v3.1
scope: service # Or application
key: service.apache.com
enabled: true
runtime: true
affinityAware:
key: region
ratio: 20
```

update condition route config design v3.1

---

registry/servicediscovery/service_discovery_registry.go

fix #2758, findMappedServices panic

fix #2758, findMappedServices panic

---

.asf.yaml

based on https://github.com/apache/cloudberry/pull/1039/files, this PR brings discussions back.

feat:add discussions

---

tools/protoc-gen-go-triple/README.md

Update protoc-gen-go-triple readme.md.

chore(readme): update protoc-gen-go-triple readme.md
