apache/dubbo-go

examples/go-client/app/config.go
examples/go-client/profiles/dev/client.yml
examples/go-client/profiles/release/client.yml
examples/go-client/profiles/test/client.yml
examples/go-server/app/config.go
examples/go-server/profiles/dev/server.yml
examples/go-server/profiles/release/server.yml
examples/go-server/profiles/test/server.yml
jsonrpc/http.go
jsonrpc/server.go
registry/consumer.go
registry/provider.go
registry/registry.go
registry/zk_client.go

client.yml & server.yaml registry_config.timeout的配置改成golang标准的duration string配置格式了，用到的地方根据自己对时间单位的需要自行转换

change client.yml & server.yaml registry_config.timeout config unit to time.duration

---

client/invoker/invoker.go
examples/dubbo/go-client/app/test.go
examples/jsonrpc/go-client/app/client.go
examples/jsonrpc/go-client/app/test.go
go.sum
registry/registry.go
registry/zookeeper/consumer.go
registry/zookeeper/listener.go
registry/zookeeper/registry.go

1.上周末一些指针引用变为对象引用，对应的listener部分没有修改完整。
2.修改了listener部分的接口定义，与java的命名一致，改为了subscribe，并且接口返回listener对象。由invoker层全面接管consumer 注册中心订阅任务的启动和监听。

upgrade registry interface definition & fix some bug

---

client/client_transport.go
client/invoker/invoker.go
client/invoker/service_array.go
client/selector/random.go
client/selector/round_robin.go
client/selector/selector.go
client/service_array.go
dubbo/client.go
examples/client_config.go
examples/dubbo/go-client/app/client.go
examples/dubbo/go-client/app/test.go
examples/jsonrpc/go-client/app/client.go
examples/jsonrpc/go-client/app/test.go
examples/jsonrpc/go-client/profiles/dev/client.yml
examples/jsonrpc/go-client/profiles/release/client.yml
examples/jsonrpc/go-client/profiles/test/client.yml
examples/jsonrpc/go-server/app/config.go
examples/jsonrpc/go-server/app/server.go
examples/jsonrpc/go-server/profiles/dev/server.yml
examples/jsonrpc/go-server/profiles/release/server.yml
examples/jsonrpc/go-server/profiles/test/server.yml
jsonrpc/http.go
jsonrpc/server.go
plugins/plugins.go
registry/event.go
registry/registry.go
registry/service.go
registry/zookeeper/consumer.go
registry/zookeeper/listener.go
registry/zookeeper/registry.go

We no longer pass the DefaultServiceConfig object in methods calling, but should pass the ServiceConfig interface  in methods calling.
And ServiceConfig can be pluginization by user who use dubbo-go now. 
You can implement the ServiceConfig interface for your own personalized needs about service configuration !

code refactor for abstracting service config's interface

---

examples/dubbo/go-client/app/user.go
examples/dubbo/go-server/app/server.go
examples/dubbo/go-server/app/user.go
examples/dubbo/java-client/src/main/java/com/ikurento/user/Consumer.java
go.mod
go.sum
protocol/dubbo/codec.go
protocol/dubbo/listener.go
registry/zookeeper/registry.go
registry/zookeeper/zk_client.go

Fix:issue #68

---

protocol/dubbo/pool.go

close client before close sessions to defeat client stop too slowly when got a signal

Fix: close client before close sessions

---

protocol/dubbo/client.go
protocol/dubbo/codec.go
protocol/dubbo/readwriter.go

fix a bug about lock when benchmark test.
Fixes #101 
@AlexStocks 
When Concurrency, this lock will not be got. The resolve case is to use sync.Map.

Fix:Lock bug

---

protocol/dubbo/client.go

解决在使用dubbo client 的 SetClientConf 函数并调用clientConf.CheckValidity() 方法后存在空指针问题
Fixes #
```release-note
```

fix dubbo clientConfig call SetClientConf func null pointer when check conf Validity

---

protocol/dubbo/server.go

修复在使用dubbo client 的 SetServerConfig 函数并调用srvConf.CheckValidity() 方法后存在空指针问题
Fixes #
```release-note
```

fix dubbo serverConfig struct point check Validity issue

---

remoting/zookeeper/listener_test.go

If we use `client.Wait.Done` in `DataChange` in the test, we may encounter the `negative watigroup counter negative`, because we invoke `client.Wait.Add` only once at
https://github.com/apache/dubbo-go/blob/1178d9a142bda19c04f49a9f584c96f68540a029/remoting/zookeeper/listener_test.go#L92
but invoke `client.Wait.Done` twice at 
https://github.com/apache/dubbo-go/blob/1178d9a142bda19c04f49a9f584c96f68540a029/remoting/zookeeper/listener_test.go#L114
and 
https://github.com/apache/dubbo-go/blob/1178d9a142bda19c04f49a9f584c96f68540a029/remoting/zookeeper/client.go#L233
So just change `client.Wait.Done` into `client.Close` in `DataChange`, then we can handle this.

avoid wg counter negative

---

common/config/environment.go
config/base_config.go
config/config_loader_test.go
config/reference_config.go
config/reference_config_test.go
config/registry_config.go
config/service_config.go
config/testdata/consumer_config.yml
registry/zookeeper/registry_test.go
remoting/zookeeper/listener.go
remoting/zookeeper/listener_test.go

New Ftr: allow user set custom params to register to registry
Fixes #
```release-note
User can set references & services params in consumer.yml & provider.yml
```

 New Ftr: allow user set custom params to register to registry

---

common/logger/logger.go

Add:GetLogger

---

common/url.go
config/registry_config.go
config/registry_config_test.go
remoting/zookeeper/client.go

Add support for zookeeper registry cluster, when zookeeper is a cluster. User can set address with multi location split with ',' 
Fixes #
```release-note
```

Add support for zookeeper registry cluster

---

go.mod
go.sum

Add support for decimal 
Fixes #109
None
```release-note
- add support for decimal
```

upgrade hessian2: support decimal

---

common/rpc_service_test.go
config_center/zookeeper/impl.go
protocol/dubbo/client_test.go
protocol/jsonrpc/json_test.go
registry/zookeeper/registry.go
registry/zookeeper/registry_test.go

Fix: ineffassign

---

remoting/zookeeper/client.go

将UnregisterEvent函数中的循环去掉，该事件意在删除满足if条件e == event的注册地址，而不是删除整个zkPath对应的注册列表。
原代码中：如果函数中a的长度是2，经过删除长度为1，能继续进入循环，但因为无满足的e == event，无法继续删除，造成死循环。
改动：函数并没有重复检查是否有zkPath的注册信息的必要，删除for循环。
Fixes #
```release-note
```

bug fix for UnregisterEvent

---

go.mod
go.sum
remoting/zookeeper/facade.go
remoting/zookeeper/listener.go

change select time.After to wheel.After
Fixes #
```release-note
```

Feature/Fix ListenDirEvent

---

cluster/loadbalance/least_active.go
cluster/loadbalance/round_robin.go
filter/impl/active_filter.go
protocol/RpcStatus.go

Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>
In the following file:
- cluster/loadbalance/least_active.go
- cluster/loadbalance/round_robin.go
- filter/impl/active_filter.go
- protocol/RpcStatus.go
the license head file as follows:
```
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and …
```

Fix license head file

---

.gitignore
cluster/cluster_impl/failback_cluster.go
cluster/cluster_impl/failback_cluster_invoker.go
cluster/cluster_impl/failback_cluster_test.go
cluster/cluster_impl/failsafe_cluster.go
cluster/cluster_impl/failsafe_cluster_invoker.go
cluster/cluster_impl/failsafe_cluster_test.go
common/constant/key.go
go.mod
go.sum

Support failback_cluster_invoker
Support failsafe_cluster_invoker
NONE
```release-note
```

[ISSUE #135] add failback_cluster_invoker && failsafe_cluster_invoker. 

---

cluster/cluster_impl/available_cluster.go
cluster/cluster_impl/available_cluster_invoker.go
cluster/cluster_impl/available_cluster_invoker_test.go

add available cluster support
```release-note
```

add available cluster support

---

go.sum
protocol/dubbo/listener.go

clean heartbea-pkg response from protocol.dubbo.Client.pendingResponses .
Fixes #163 
```release-note
```

[ISSUE #163] clean heartbeat from PendingResponse

---

remoting/zookeeper/listener.go

Fix zk high memory bug in event listener.
Fixes #
```release-note
```

Fix:zk high memory bug 

---

registry/zookeeper/listener.go
registry/zookeeper/registry.go

zk log change

---

cluster/cluster_impl/forking_cluster.go
cluster/cluster_impl/forking_cluster_invoker.go
cluster/cluster_impl/forking_cluster_test.go
common/constant/key.go
config/reference_config_test.go
config/testdata/consumer_config.yml

add forkingClusterInvoker
Fixes #

add forkingClusterInvoker

---

common/url.go

Url.Values is not safe map, so add the lock to avoid concurrent map read and map write error
Fixes #
```release-note
```

Fix:url.Values is not safe map

---

protocol/dubbo/pool.go

Fix: gettyRPCClientPool.remove deadlock

---

protocol/dubbo/pool.go

Imp: split protocol/dubbo/pool.go gettyRPCClient.close and gettyRPCClientPool.remove

Imp: split protocol/dubbo/pool.go gettyRPCClient.close and gettyRPCClientPool.remove

---

examples/consul/go-server/server.go
examples/generic/go-client/app/client.go
examples/hystrixfilter/dubbo/with-hystrix-go-client/app/client.go

remove `go` before `time.time.AfterFunc`
Fixes https://github.com/apache/dubbo-go/issues/176.
```release-note
None
```

Fix: tim.AfterFunc do not need to run in another goroutine

---

protocol/dubbo/pool.go

remove client from pool before closing it to ensure other task can not got it.

Imp:  remove client from pool before closing it

---

common/url.go
common/url_test.go
protocol/protocolwrapper/protocol_filter_wrapper.go
registry/consul/utils.go
registry/directory/directory_test.go
registry/etcdv3/registry.go
registry/etcdv3/registry_test.go
registry/nacos/registry.go
registry/nacos/registry_test.go
registry/zookeeper/registry.go
registry/zookeeper/registry_test.go

Fix fix url params unsafe completely.
Fixes #200 
```release-note
```

Fix:fix url params unsafe

---

protocol/dubbo/client.go
protocol/dubbo/server.go

fix issue:#204, branch develop

fix issue:204, branch develop

---

CHANGE.md
README.md
README_CN.md
common/constant/default.go
common/constant/key.go
common/url.go
config/service_config.go
examples/helloworld/dubbo/go-server/profiles/dev/server.yml
filter/impl/token_filter.go
filter/impl/token_filter_test.go
go.mod
protocol/dubbo/dubbo_invoker.go

Add token support
```release-note
```

Add token support

---

cluster/cluster_impl/failover_cluster_invoker.go
go.mod
go.sum
protocol/dubbo/readwriter.go
registry/protocol/protocol.go

1. update getty&hessian version
2. fix bug about registryProtocol.Export
3. fix bug for failover_cluster_invoker.go
Fixes #

Imp & Fix: issue #217

---

config/protocol_config.go

Fix load protocol
Fixes #
Yes.
User's server.yaml which defined as 
```
services:
"UserProvider":
protocol : "myDubbo"
xxxx
```
protocol value should match key in protocols map defined as follow.
```
protocols:
"myDubbo":
name: "dubbo"
ip : "127.0.0.1"
port : 20000
````
```release-note
```

Fix:load protocol

---

protocol/dubbo/client.go

[Fix]fix dubbo group issues#238

---

registry/protocol/protocol.go
registry/protocol/protocol_test.go

It seems that the registryProtocol should be a singleton. The method GetProtocol doesn't set the value after it creates an instance of registryProtocol. So every time we invoke extension.GetProtocol("registry"), we will get different instances.
But the registryProtocol mantains all the instances of Registry, it should be a singleton.
Fixes #
```release-note
```

Fix: The registryProtocol should be singleton

---

config/reference_config.go

The lack of ',' between generic filter and default reference filters
Fixes #
```release-note
```

Fix BUG:  The generic filter and default reference filters lack ','

---

config/graceful_shutdown.go
config/graceful_shutdown_signal_unix.go
config/graceful_shutdown_signal_windows.go

The SIGSYS and SIGSTOP are not supported in the Windows platform, so we should define the signals we catch on different platforms.
Fixes #
```release-note
```

Fix BUG: The SIGSYS and SIGSTOP are not supported in windows platform

---

registry/protocol/protocol.go
registry/protocol/protocol_test.go

It seems that we can not change the registryProtocol to be a singleton. If we do that, the listen, especially zk registry listener, doesn't work well.
Fixes #
```release-note
```

Fix: Revert the registryProtocol.GetProtocol() to its original codes

---

config_center/parser/configuration_parser.go

Signed-off-by: imxyb <xyb4638@gmail.com>
should return error when `NewURL` failed.
Fixes #
```release-note
```

should return error when `NewURL` failed.

---

registry/zookeeper/listener.go
registry/zookeeper/registry.go

fix https://github.com/apache/dubbo-go/issues/259#issue-527128370
Fixes #
```release-note
```

Fix: After disconnection with ZK registry, cosumer can't listen to provider changes

---

common/logger/logger.go
common/logger/logger_test.go

add `SetLoggerLevel` to dynamically modify logger level.

Add: add SetLoggerLevel

---

common/extension/tps_limit.go
filter/impl/tps/impl/tps_limit_fix_window_strategy.go
filter/impl/tps/impl/tps_limit_fix_window_strategy_test.go
filter/impl/tps/impl/tps_limit_sliding_window_strategy.go
filter/impl/tps/impl/tps_limit_sliding_window_strategy_test.go
filter/impl/tps/impl/tps_limit_thread_safe_fix_window_strategy.go
filter/impl/tps/impl/tps_limit_thread_safe_fix_window_strategy_test.go
filter/impl/tps/impl/tps_limiter_method_service.go
filter/impl/tps/impl/tps_limiter_method_service_test.go
filter/impl/tps/tps_limit_strategy.go

Now, the tps-limit's extension accepts `func(rate int, interval int)tps.TpsLimitStrategy` as the creator of TpsLimitStrategy.
It's bad-smell code. So this PR define the TpsStrategyCreator interface to replace them.
Fixes #
```release-note
```

Ftr: Replace func(int, int) with TpsLimitStrategyCreator interface

---

cluster/loadbalance/consistent_hash.go
cluster/loadbalance/consistent_hash_test.go
common/constant/default.go
go.mod

Signed-off-by: imxyb <xyb4638@gmail.com>
add consistent hash load balance
Fixes #
```release-note
```

consistent hash load balance

---

filter/impl/tps/impl/tps_limiter_method_service_test.go
registry/zookeeper/listener.go

Last time I try to fix #252 but the solution has a problem that in a concurrent environment the listener will be closed twice too. So I add a closeOncy to ensure it should be closed at most once.
Fixes #252 
```release-note
```

fix: zkRegistry.Destroy() -- negative Waitgroup counter

---

registry/zookeeper/registry.go
remoting/zookeeper/listener_test.go

be consistent with java impl, support url encoder for zkpath

feat(registry/zk):url encode zkpath

---

cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/base_cluster_invoker_test.go
cluster/cluster_impl/failback_cluster_test.go
cluster/cluster_impl/failfast_cluster_test.go
cluster/cluster_impl/failsafe_cluster_test.go
common/constant/key.go
common/url.go
common/url_test.go
config/method_config.go
config/reference_config.go
config/reference_config_test.go

support sticky connection

---

protocol/dubbo/pool.go
registry/protocol/protocol.go
registry/protocol/protocol_test.go

change the position of the lock

---

config_center/apollo/impl_test.go

delete mock json in test case of apollo when cases finished
Fixes #
```release-note
```

Add : delete mock json in test case of apollo

---

config/service_config.go
config/service_config_test.go

When service don't have right protocol config, remind user to check.
Fixes #308
```release-note
```

When service don't have right protocol config, remind user to check.

---

config/config_center_config.go
config_center/apollo/impl.go
config_center/apollo/impl_test.go

zookeeper config center can't use when added  item key which is configcenter.namepace in config file
reason:
zookeeper use namespace key but have not  add to config file
ref:
https://github.com/apache/dubbo-go/blob/cabd56a95cd775ebd976c2b29c5ff95260986d61/config_center/zookeeper/impl.go#L59
Fixes #
```release-note
```

Fix:zookeeper config center namespace default value invalid

---

remoting/zookeeper/client.go
remoting/zookeeper/listener.go

1.exit listen when zk.errNilNode happen
2.Ftr the lock of ZookeeperClient
Fixes #
```release-note
```

Fix : zk problem

---

config_center/zookeeper/impl.go
config_center/zookeeper/impl_test.go
go.mod
go.sum
registry/base_register.go
registry/etcdv3/listener.go
registry/etcdv3/registry.go
registry/etcdv3/registry_test.go
registry/registry.go
registry/zookeeper/listener.go
registry/zookeeper/registry.go
registry/zookeeper/registry_test.go
remoting/etcdv3/client.go
remoting/etcdv3/facade.go
remoting/etcdv3/listener.go
remoting/listener.go
remoting/zookeeper/client.go
remoting/zookeeper/client_test.go
remoting/zookeeper/facade.go
remoting/zookeeper/facade_test.go
remoting/zookeeper/listener.go
remoting/zookeeper/listener_test.go

add zk register code

---

protocol/dubbo/client.go

do not close conn when can not get response in protocol/dubbo/client.go

Fix: do not close conn when can not get response

---

protocol/dubbo/dubbo_invoker.go
registry/directory/directory.go

Fix:deal the panic when invoker destroy

---

protocol/rest/rest_config_reader/default_config_reader_test.go

Fix Rest protocol

---

.gitignore

Even base on `develop` branch, the temp JSON file is still on the fly after the ut process finished
```
On branch develop
Untracked files:
(use "git add <file>..." to include in what will be committed)
config_center/apollo/mockDubbog.properties.json
nothing added to commit but untracked files present (use "git add" to track)
```
One possible reason is that the [100ms](https://github.com/apache/dubbo-go/blob/master/config_center/apollo/impl_test.go#L271) is not long enough to wait until the JSON file creation process done from another goroutine.

fix(apollo/ut): ignore apollo property file which generated by ut

---

.travis.yml

Add more CI jobs to cover both `go1.12` and `go1.13` for `osx` and `linux`.

Improve: add more ci environments

---

remoting/etcdv3/client_test.go

Add up more assertations for the etcdv3 client.

Fix remoting/etcdv3/client test cases

---

go.mod
go.sum
protocol/dubbo/client.go
protocol/dubbo/listener.go
protocol/dubbo/pool.go

1 Imp: trace error of getGettyRpcClient
2 update dubbogo/getty to latest version
3 update apache/dubbo-go-hessian2 to latest version

Imp: trace error of getGettyRpcClient

---

CHANGE.md
README.md
README_CN.md
protocol/grpc/protoc-gen-dubbo/examples/helloworld.proto
registry/directory/directory.go

merge 1.3
Fixes #
```release-note
```

Mrg: merge 1.3

---

protocol/rest/rest_client/resty_client.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol_test.go

Fix client hasn't read error msg in rest protocol

---

protocol/rest/rest_protocol.go

Fix problem of rest protocol PR #352

---

common/proxy/proxy.go
config/generic_service.go

user can add attachment

---

config_center/parser/configuration_parser.go

Mod: delete a judgment condition

---

common/rpc_service.go
config/reference_config.go
config_center/zookeeper/impl.go
registry/base_registry.go
registry/protocol/protocol.go
registry/zookeeper/listener.go
registry/zookeeper/listener_test.go
registry/zookeeper/registry.go
remoting/zookeeper/client.go
remoting/zookeeper/facade.go
remoting/zookeeper/facade_test.go
remoting/zookeeper/listener.go
remoting/zookeeper/listener_test.go

1. modify registryProtocol as a singleton to fix graceful shutdown can't delete the provider url
2. fix notification confusion caused by multiple references sharing the same zk listener

Fix: issue #32

---

common/constant/key.go
config/metadata_report_config_test.go
go.mod
go.sum
metadata/identifier/subscribe_metadata_identifier.go
registry/nacos/service_discovery.go

update hessian2 & getty version.

Update: hessian2 & getty version

---

common/url.go
config/config_loader.go

Divide load process to consumer && provider processes
Add comment for URLEqual
Fixes #
```release-note
```

a little refactor

---

config_center/nacos/impl.go
config_center/nacos/impl_test.go
go.mod
go.sum

Implement the method GetConfigKeysByGroup because nacos client provided the batch API

implement GetConfigKeysByGroup

---

common/constant/key.go
common/proxy/proxy.go
common/proxy/proxy_factory/default.go

before this , consumer can send attachment from context
after this
Provider get attachment in context

provider can get attachment in ctx

---

common/constant/key.go
go.sum
registry/base_registry.go
registry/consul/registry.go
registry/consul/registry_test.go
registry/etcdv3/registry.go
registry/kubernetes/registry.go
registry/mock_registry.go
registry/nacos/registry.go
registry/protocol/protocol.go
registry/protocol/protocol_test.go
registry/registry.go
registry/zookeeper/listener.go
registry/zookeeper/registry.go
registry/zookeeper/registry_test.go
remoting/zookeeper/listener.go

* add UnRegister and UnSubscribe for Registry
Fixes #489
```release-note
```

Ftr : add UnRegister and UnSubscribe for zookeeper Registry

---

integrate_test.sh
test/integrate/dubbo/go-client/Dockerfile
test/integrate/dubbo/go-server/Dockerfile

The previous PR https://github.com/apache/dubbo-go/pull/520
had some scenarios that were not considered, which led to errors in integration testing when the PR was merged into the local branch.
Fixes #
```release-note
```

Ftr: Add integrate test

---

registry/zookeeper/listener.go
registry/zookeeper/registry.go
registry/zookeeper/registry_test.go

* Change subscribe service key in registrydatalistener 
subscribe service key cannot use pointer, maybe different pointers between subscribe and unsubscribe
Fixes #
```release-note
```

Rft : Change subscribe service key in registrydatalistener

---

config/metadata_report_config.go
registry/directory/directory.go
registry/directory/directory_test.go

optimize error handling
Fixes #
```release-note
```

Opt: opt err handling

---

protocol/invocation.go
protocol/invocation/rpcinvocation.go

Some parameter need to be used in the internal process.  For example we need calculate the serialize type and store into attribute. If we don't store it and this serialize value is used by some function or method , we must calculate it in every function.

Add attribute method into Invocation and RpcInvocation

---

config_center/apollo/listener.go
config_center/configuration_listener.go
config_center/configurator.go
config_center/configurator/mock.go
config_center/dynamic_configuration.go
config_center/dynamic_configuration_factory.go
config_center/mock_dynamic_config.go
config_center/parser/configuration_parser.go
config_center/zookeeper/listener.go

Add comments for config_center
Fixes #
```release-note
```

Add comments for config_center

---

metrics/prometheus/reporter.go
metrics/reporter.go

Mod: Updated the comments in metrics, corrected the grammar.

Mod: update the comments in metrics

---

common/extension/registry.go

modify_registry_panic_msg
Fixes #
no
```release-note
```

Rft: modify registry panic msg

---

cluster/cluster.go
cluster/cluster_impl/available_cluster.go
cluster/cluster_impl/available_cluster_invoker.go
cluster/cluster_impl/broadcast_cluster.go
cluster/cluster_impl/failback_cluster.go
cluster/cluster_impl/failfast_cluster.go
cluster/cluster_impl/failover_cluster.go
cluster/cluster_impl/failsafe_cluster.go
cluster/cluster_impl/forking_cluster.go
cluster/cluster_impl/mock_cluster.go
cluster/cluster_impl/registry_aware_cluster.go
cluster/directory.go
cluster/loadbalance.go
cluster/loadbalance/consistent_hash.go
cluster/loadbalance/least_active.go
cluster/loadbalance/random.go
cluster/loadbalance/round_robin.go
cluster/loadbalance/util.go

add comment for cluster directory
Fixes #
```release-note
```

Ftr: add comment for cluster

---

common/extension/auth.go
filter/access_key.go
filter/authenticator.go
filter/filter.go
filter/filter_impl/active_filter.go
filter/filter_impl/auth/accesskey_storage.go
filter/filter_impl/auth/consumer_sign.go
filter/filter_impl/auth/default_authenticator.go
filter/filter_impl/auth/provider_auth.go
filter/filter_impl/auth/sign_util.go
filter/filter_impl/echo_filter.go
filter/filter_impl/execute_limit_filter.go
filter/filter_impl/generic_filter.go
filter/filter_impl/graceful_shutdown_filter.go
filter/filter_impl/hystrix_filter.go
filter/filter_impl/token_filter.go
filter/filter_impl/tps/tps_limit_fix_window_strategy.go
filter/filter_impl/tps/tps_limit_sliding_window_strategy.go
filter/filter_impl/tps/tps_limit_thread_safe_fix_window_strategy.go
filter/filter_impl/tps/tps_limiter_method_service.go
filter/filter_impl/tps_limit_filter.go
filter/handler/rejected_execution_handler_only_log.go
filter/rejected_execution_handler.go
filter/tps_limit_strategy.go
filter/tps_limiter.go

Added comments to filter directory
Fixes #569

Mod: update the comments in filter directory

---

config_center/dynamic_configuration_test.go
config_center/nacos/client_test.go
config_center/nacos/impl_test.go
config_center/parser/configuration_parser_test.go

Improve code coverage of nacos config center and configuration parser
relates #518

Improve code coverage of nacos config center and configuration parser

---

metadata/report/nacos/report.go
metadata/report/nacos/report_test.go
registry/nacos/base_registry.go
remoting/nacos/builder.go

Implement MetadataReport based on Nacos
Fixes #446

Nacos MetadataReport implementation

---

cluster/cluster_impl/available_cluster_invoker_test.go
cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/base_cluster_invoker_test.go
cluster/cluster_impl/broadcast_cluster_invoker_test.go
cluster/cluster_impl/failback_cluster_invoker.go
cluster/cluster_impl/failback_cluster_test.go
cluster/cluster_impl/failfast_cluster_test.go
cluster/cluster_impl/failover_cluster_invoker.go
cluster/cluster_impl/failover_cluster_test.go
cluster/cluster_impl/failsafe_cluster_test.go
cluster/cluster_impl/forking_cluster_invoker.go
cluster/cluster_impl/forking_cluster_test.go
cluster/cluster_impl/registry_aware_cluster_test.go
cluster/directory/base_directory_test.go
cluster/directory/static_directory_test.go
cluster/loadbalance/least_active_test.go
cluster/loadbalance/random_test.go
cluster/loadbalance/round_robin_test.go
cluster/router/chain/chain_test.go
cluster/router/condition/app_router_test.go
cluster/router/condition/factory_test.go
cluster/router/healthcheck/default_health_check_test.go
cluster/router/healthcheck/factory_test.go
cluster/router/healthcheck/health_check_route_test.go
common/constant/default.go
common/extension/config_center.go
common/url_test.go

1. modify part of code style 
Fixes #514
```release-note
```

Imp: modify codes by code review of gitee

---

before_ut.bat
common/constant/key.go
config/config_center_config.go
config_center/nacos/client.go

- fix logDir path seperator in Windows
- fix unit test prepare script for Windows
Fixes #
no

Fix: Nacos client logDir path seperator

---

protocol/dubbo/client.go
protocol/dubbo/codec.go
protocol/dubbo/config.go
protocol/dubbo/dubbo_protocol.go
protocol/dubbo/listener.go
protocol/grpc/client.go
protocol/grpc/grpc_exporter.go
protocol/grpc/grpc_invoker.go
protocol/grpc/grpc_protocol.go
protocol/grpc/internal/server.go
protocol/grpc/server.go
protocol/invocation.go
protocol/invocation/rpcinvocation.go
protocol/invoker.go
protocol/jsonrpc/http.go
protocol/jsonrpc/json.go
protocol/jsonrpc/jsonrpc_exporter.go
protocol/jsonrpc/jsonrpc_invoker.go
protocol/jsonrpc/jsonrpc_protocol.go
protocol/jsonrpc/server.go
protocol/protocol.go
protocol/protocolwrapper/mock_protocol_filter.go
protocol/protocolwrapper/protocol_filter_wrapper.go
protocol/result.go
protocol/rpc_status.go

* update the comments in protocol directory 
Fixes #
```release-note
```

Mod: update the comments in protocol directory 

---

registry/etcdv3/registry.go
remoting/etcdv3/client.go
remoting/etcdv3/facade.go
remoting/etcdv3/listener.go
remoting/kubernetes/client.go
remoting/kubernetes/listener.go
remoting/kubernetes/registry_controller.go
remoting/kubernetes/watch.go
remoting/listener.go
remoting/zookeeper/client.go
remoting/zookeeper/facade.go
remoting/zookeeper/listener.go

add comments for remoting
Fixes #
```release-note
```

Mod: add comments for remoting

---

remoting/zookeeper/client.go
remoting/zookeeper/client_test.go

- add lock for `eventRegistry` in `ZookeeperClient ` to avoid concurrent read and write in map
- replace `github.com/stretchr/testify/assert` with `github.com/stretchr/testify/require`  in test to fail test case immediately when test meet an error
- fix type and remove `\n` in log
- NONE
```release-note
NONE
```

Imp: Zk client

---

protocol/invocation/rpcinvocation.go

现在逻辑里rpcInvocation里没有invoker参数，需要支持设置

add setInvoker method for invocation

---

config_center/configuration_listener.go
registry/base_configuration_listener.go
registry/consul/listener.go
registry/consul/registry.go
registry/directory/directory.go
registry/etcdv3/listener.go
registry/etcdv3/registry.go
registry/event.go
registry/event_listener.go
registry/kubernetes/listener.go
registry/kubernetes/registry.go
registry/mock_registry.go
registry/nacos/listener.go
registry/nacos/registry.go
registry/nacos/service_discovery.go
registry/nacos/service_discovery_test.go
registry/protocol/protocol.go
registry/registry.go
registry/service_discovery.go
registry/service_instance.go
registry/zookeeper/registry.go

* update the comments in registy directory
Fixes #
```release-note
```

Mod: update the comments in registy directory

---

config_center/apollo/impl_test.go
config_center/configurator/override.go
config_center/configurator/override_test.go
config_center/mock_dynamic_config.go
config_center/nacos/client_test.go
config_center/nacos/impl_test.go
config_center/nacos/listener.go
config_center/parser/configuration_parser_test.go
config_center/zookeeper/impl_test.go

Imp: fix various linter warnings

---

cluster/directory/base_directory.go
cluster/router/chain/chain.go
cluster/router/chain/chain_test.go
cluster/router/chan.go
cluster/router/condition/factory.go
cluster/router/condition/factory_test.go
cluster/router/healthcheck/health_check_route.go
cluster/router/router.go
cluster/router/tag/factory.go
cluster/router/tag/factory_test.go
common/extension/router_factory.go

* Extract priority router 
Fixes #477 
```release-note
```

Rft : Extract priority router

---

common/constant/default.go
registry/base_configuration_listener.go

Add anyhost judgment in ToConfigurators in registry/base_configuration_listener.go, which is used to improve code quality by removing 'TODO' comment
Fixes #
```release-note
NONE
```

Add: anyhost key judgment

---

.gitignore
README.md
README_CN.md
common/constant/default.go
filter/filter_impl/access_log_filter_test.go
filter/filter_impl/active_filter_test.go
filter/filter_impl/echo_filter_test.go
filter/filter_impl/execute_limit_filter_test.go
filter/filter_impl/generic_filter_test.go
filter/filter_impl/generic_service_filter_test.go
filter/filter_impl/graceful_shutdown_filter_test.go
filter/filter_impl/hystrix_filter_test.go
filter/filter_impl/metrics_filter_test.go
filter/filter_impl/token_filter_test.go
filter/filter_impl/tps/tps_limit_fix_window_strategy_test.go
filter/filter_impl/tps/tps_limit_sliding_window_strategy_test.go
filter/filter_impl/tps/tps_limit_thread_safe_fix_window_strategy_test.go
filter/filter_impl/tps/tps_limiter_method_service_test.go
filter/filter_impl/tps_limit_filter_test.go
filter/filter_impl/tracing_filter_test.go
registry/base_configuration_listener.go

* merge master commit to develop
Fixes #
```release-note
```

Fix: Merge master commit to develop

---

filter/filter_impl/seata_filter.go
filter/filter_impl/seata_filter_test.go

support distributed transaction, by experimentally [seata-golang](https://github.com/dk-lockdown/seata-golang)
this pr just added a filter, to receive xid from attachments

Ftr: experimentally distributed transaction based on seata-golang

---

protocol/rest/server/server_impl/go_restful_server.go
protocol/rest/server/server_impl/go_restful_server_test.go

now if we config this
```
"UserProvider":
protocol : "rest"
interface : "com.ikurento.user.UserProvider"
rest_path: "/UserProvider"
methods:
- name: "GetUser"
rest_path: "/GetUser"
rest_method: "GET"
rest_query_params: "0:id"
- name: "GetUser0"
rest_path: "/GetUser"
rest_method: "POST"
rest_produces: "application/json"
rest_consumes: "application/json;charset=utf-8,*/*"
```
Some error was happen.
make GoRestServer support to deploy the HTTP interfaces with same path and different method type

Fix: GoRestServer can't deploy the HTTP interfaces with same path and different method type

---

remoting/kubernetes/listener_test.go

fix kubernetes remoting pkg ut bug
Fixes #
```release-note
```

Fix k8s ut bug

---

README.md
README_CN.md
common/constant/default.go
common/constant/key.go
config/registry_config.go
registry/zookeeper/registry.go
remoting/zookeeper/listener.go

Fix: zk lost event

---

config/base_config.go
config/base_config_test.go
config/config_center_config.go
config/config_center_config_test.go
config/consumer_config.go
config/provider_config.go
config/remote_config.go

* optimize remotes configuration
* refactor config center implement.
* will compatible with `baseConfig.ConfigCenterConfig.Address` and `baseConfig.ConfigCenterConfig.RemoteRef` before 1.6.0. After 1.6.0 will not compatible, only `baseConfig.ConfigCenterConfig.RemoteRef`.
Fixes #501
```release-note
```

Rft: Optimize remotes configuration

---

cluster/directory/base_directory.go
cluster/directory/base_directory_test.go
cluster/router/chain/chain_test.go
cluster/router/condition/app_router_test.go
cluster/router/condition/file.go
cluster/router/condition/file_test.go
cluster/router/condition/router.go
cluster/router/condition/router_rule.go
cluster/router/condition/router_rule_test.go
cluster/router/condition/router_test.go
cluster/router/tag/router_rule.go
common/constant/key.go
common/url.go
common/yaml/yaml.go
config/router_config.go
config/router_config_test.go
config/service_config_test.go
config/testdata/router_config_error.yml
config/testdata/router_multi_config.yml

1. Support multiple routers configuration in router_config.yml
2. Apply prioritization to routers
3. Enable service level routers
Fixes #596
After this change, the local router configuration file needs to follow below pattern to support multiple routing rules in local file configuration:
```release-note
routerRules: 
- scope: application
key: mock-app1
priority: 1
force: true
conditions :
- "a => b"
- "c => d"
- scope: application
key: mock-app2
priority: 1
force: true
conditions :
- "a => b"
- "c => d"
```
the scope defines the rule's applicable range, 'application' | 'service'
the key defines the rule's applicable application name(for …

Ftr: Feature/application and service level router

---

cluster/directory/base_directory.go

Retrieve the directory's services' application name from suburl.
Fixes #
```release-note
```

Fix: application router get application name from dir.url and dir.url.suburl

---

registry/nacos/listener.go

Call subscribe function asynchronously to avoid blocking handle change event.

call subscribe function asynchronously

---

filter/filter_impl/hystrix_filter.go

This PR fixes a problem that config related functions try to read **consumer** config when using HystrixFilter on **provider** side. 
Fixes #710 
Fixes #666 
```release-note
Some comments are also added in hystrix_filter to help use this filter
```

Fix: fix init config problem in HystrixFilter

---

cluster/router/tag/tag_router.go
common/rpc_service.go
common/url.go
config/base_config.go
config/reference_config.go
config_center/configurator/override.go
protocol/rest/rest_exporter.go
registry/etcdv3/listener_test.go
registry/event/service_revision_customizer.go
registry/protocol/protocol.go
remoting/zookeeper/curator_discovery/service_discovery.go

**What this PR does**: Sharp the code.
**Which issue(s) this PR fixes**: Readable code.
Fixes #
```release-note
```

Mod: Remove unnecessary return and judgement.

---

common/rpc_service.go
config/config_loader.go
config/consumer_config.go
config/provider_config.go
config/service_config.go
metadata/service/exporter/configurable/exporter.go
protocol/jsonrpc/jsonrpc_protocol.go
protocol/jsonrpc/server.go
protocol/protocolwrapper/protocol_filter_wrapper.go
registry/protocol/protocol.go
registry/registry.go

- code format
- fix bug in [service_config.go](https://github.com/apache/dubbo-go/blob/develop/config/service_config.go#L201-L225):
在`if len(regUrls) > 0`的分支里面，对`regUrls`进行循环，其中每个`regUrl`生成的`exporter`都应该放到`append`到`exporters`里面。但是现在的代码里面只有最后一个`append`到`exporters`里面了。
所以应该在代码的`216`行下面加一个`c.exporters = append(c.exporters, exporter)`。

fix exporter append

---

protocol/rpc_status.go

This PR is to improve the accessing of map in concurrency environment.
1. improve the performace of GetURLStatus() method
2. fix the problem of concurrency risk in  GetMethodStatus() method
Fixes #
```release-note
NONE
```

Imp: Improve map access concurrency

---

registry/directory/directory.go
registry/protocol/protocol.go
registry/registry.go

Support address notification from registry center in batch mode, instead of omit from register center one by one. In this mode, we assume all events accumulated by registry center first, then registry center will notify the directory the complete list in batch mode.
Fixes #
```release-note
```

Address notification batch mode

---

cluster/router/healthcheck/default_health_check.go
common/extension/health_checker.go
common/extension/health_checker_test.go

Rename SethealthChecker to SetHealthChecker
Fixes #
```release-note
```

Fix: rename SethealthChecker to SetHealthChecker

---

common/proxy/proxy_factory/default.go
registry/protocol/protocol.go

In the code, it is a conversion 
```
ivk.invoker.(*proxy_factory.ProxyInvoker).BaseInvoker
```
If I want to extend the ProxyInvoker, some error happend.

ProxyInvoker cannot be extended 

---

registry/etcdv3/registry.go
remoting/etcdv3/client.go

Fix: add etcdv3 lease to defeat provider register info left in the registry when provider app  panic

---

common/constant/key.go
common/url.go
config_center/apollo/impl.go
config_center/base_dynamic_configuration.go
config_center/dynamic_configuration.go
config_center/file/factory.go
config_center/file/impl.go
config_center/file/impl_test.go
config_center/file/listener.go
config_center/mock_dynamic_config.go
config_center/nacos/impl.go
config_center/zookeeper/impl.go
go.mod
registry/file/listener.go
registry/file/service_discovery.go
registry/file/service_discovery_test.go

The implementation of ServiceDiscovery based on file system.
Fixes #426
```release-note
```

Ftr: File system service discovery 

---

.github/workflows/go.yml

The reminders of GithubActions Robots are richer.
**Badge:** ![CI](https://github.com/apache/dubbo-go/workflows/CI/badge.svg)

CI: Enhance DingTalk reminder information.

---

protocol/dubbo/dubbo_codec.go
remoting/getty/config.go
remoting/getty/readwriter.go

add some comments
Fixes #
```release-note
```

Refact seri

---

registry/nacos/registry.go

fix nacos registry can not get namespaceId from RegistryConfig params
I use code configurations instead of configuration files in my projects
NONE
```release-note
```

Fix: nacos registry can not get namespaceId

---

common/url.go

fix url.params fatal error: concurrent map read and map write
https://github.com/apache/dubbo-go/issues/772

Fix: url.params fatal error: concurrent map read and map write

---

common/proxy/proxy_factory/default.go
protocol/grpc/protoc-gen-dubbo/plugin/dubbo/dubbo.go

增加了dubbo-gen的stream类型支持
#770 
修改了grpc/protoc-gen-dubbo/dubbo/dubbo.go内关于stream类型的pb.go文件生成。
主要修改了grpc.StreamDesc{}结构关于stream类型的服务发现支持。
可直接使用grpc提供的stream服务达到客户端与服务端交互的目的
NONE
```release-note
```

[Ftr]: dubbo-gen  stream support

---

registry/base_registry.go

fix that “,” code twice become “%252”.

Fix:fixed url encode

---

cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/failover_cluster_invoker.go
cluster/directory/base_directory_test.go
cluster/router/condition/factory_test.go
cluster/router/condition/router.go
common/host_util.go
common/host_util_test.go
config/config_loader.go
config/service_config_test.go
config_center/configurator/override.go
registry/base_registry.go
registry/consul/utils.go
registry/directory/directory.go
registry/kubernetes/registry.go
registry/nacos/registry.go

when it need local ip, it will get it every time. We can get local ip once, and reused it.

---

cluster/router/healthcheck/default_health_check.go
protocol/dubbo/dubbo_invoker.go
remoting/exchange_client.go
remoting/getty/getty_client.go

when the server is down by accident, we need a mechanism to detect this situation quickly, so that the health check router will not route the request to the problematic provider.
Fixes #
```release-note
```

enhance client's connectivity

---

remoting/exchange_client.go

* The reason as below :
When delete provider node will close getty_client and set getty_pool to nil. 
https://github.com/apache/dubbo-go/blob/1268a960bc7bdcd9457edca29f498e0ca42d0072/remoting/exchange_client.go#L182
However ExchangeClient.init is false cause getty_pool will not re-init when re-request.
https://github.com/apache/dubbo-go/blob/1268a960bc7bdcd9457edca29f498e0ca42d0072/remoting/exchange_client.go#L61
Then getty_pool is nil when re-request, detail as below
Solution：
* Change  a flag for re-init getty_pool
Fixes #
```release-note
```

Fix: Consumer panic when restart provider 

---

cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/failover_cluster_invoker.go
cluster/directory/base_directory_test.go
cluster/router/condition/factory_test.go
cluster/router/condition/router.go
common/host_util.go
common/host_util_test.go
config/config_loader.go
config/service_config_test.go
config_center/configurator/override.go
registry/base_registry.go
registry/consul/utils.go
registry/directory/directory.go
registry/kubernetes/registry.go
registry/nacos/registry.go

Imp: get local ip once and reused it

---

go.mod
go.sum

Upgrade sentinel go to v0.6.2 to degrade system module in windows OS
None
@AlexStocks 
```release-note
Upgrade sentinel go to v0.6.2 to degrade system module in windows OS
```

fix sentinel windows issue

---

filter/filter_impl/generic_filter.go
filter/filter_impl/generic_filter_test.go

fix generic struct2MapAll
Fixes #801

fix generic struct2MapAll

---

remoting/etcdv3/facade.go

fix etcd cluster reconnect
Fixes #
```release-note
```

Fix: etcd cluster reconnect

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml

* Add auto security check, will create security check report  automatically as below
https://github.com/zouyx/dubbo-go/security/code-scanning
* Add auto dependency updates, will create PR of  dependency updates automatically as below
https://github.com/zouyx/dubbo-go/pulls
Fixes #
```release-note
```

Ftr: Add more automatic components

---

common/constant/key.go
config/service_config.go
protocol/grpc/client.go
protocol/grpc/grpc_protocol.go
protocol/grpc/server.go

增加“在配置文件中设置grpc max message size“”的功能。
Fixes #806 
在Service中增加标签为 max_message_size的字段，在开启grpc server时作为参数传入，并写入invoker用于暴露。
客户端拿到服务端url后会更新本地invoker，grpc client会自动调整为与服务端message_size一致。
NONE
```release-note
```

Ftr: Add grpc max message size config

---

go.mod
go.sum

`github.com/shirou/gopsutil` in sentinel-golang use the same as another package
* `github.com/shirou/gopsutil` in sentinel-golang has a bug as below, cause can not compile in darwin.
ref：https://github.com/shirou/gopsutil/issues/919
```release-note
```

Fix:github.com/shirou/gopsutil can not compile in darwin

---

registry/zookeeper/listener.go
registry/zookeeper/registry.go

Remove the unmeaning variables in RegistryDataListener and change unlock to defer.

Remove unmeaning logic

---

protocol/dubbo/impl/hessian.go

When dubbogo(develop branch)  call dubbo(2.7.7), if params is struct, will error: 
```bash
2020-12-02T18:29:34.332+0800    ERROR   dubbo/dubbo_codec.go:249        pkg.Unmarshal(len(@data):0) = error:java exception:Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:com.funnycode.DemoService, sayHello
java.lang.IllegalArgumentException: Service not found:com.funnycode.DemoService, sayHello
at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:134)
at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:80)
at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
at …
```

[Fix] struct javaclassname 2 dubbo provider

---

config/router_config.go

fix bug
Fixes #
```release-note
```

fix: fix router_config add &url to url

---

common/url.go
common/url_test.go

Optimize some memory usage issue , please refer to #901 
In this way, we can remove some lock for it is cloned in MergeURL
Fixes #901 
```release-note
```

#901 Optimize the memory usage.

---

cluster/router/chain/chain.go
registry/directory/directory_test.go

* Router chain can build immediately when started
Fixes #
```release-note
```

Fix: Router chain can not build immediately when started

---

common/url.go
common/url_test.go

What this PR does:
Optimize some memory usage issue , please refer to #901
In this way, we can remove some lock for it is cloned in MergeURL
Which issue(s) this PR fixes:
Fixes #901
Special notes for your reviewer:
Does this PR introduce a user-facing change?:

Optimize the memory usage

---

common/url.go

fix:  URL.String() data race panic

---

common/extension/config_post_processor.go
config/config_post_processor.go
config/interfaces/config_post_processor.go
config/reference_config.go
config/service_config.go

introduce ConfigPostProcessor extension so that user can customize configs for both ServiceConfig and ReferenceConfig further during deployment time. 
Fixes #
```release-note
```

introduce ConfigPostProcessor extension

---

common/proxy/proxy_factory/default.go
common/rpc_service.go
common/rpc_service_test.go
common/url.go
config/config_loader_test.go
config/reference_config.go
config/service_config.go
filter/filter_impl/access_log_filter.go
filter/filter_impl/generic_service_filter.go
filter/filter_impl/generic_service_filter_test.go
metadata/definition/definition_test.go
metadata/report/delegate/delegate_report_test.go
metadata/service/exporter/configurable/exporter_test.go
metadata/service/inmemory/service.go
metadata/service/inmemory/service_test.go
metadata/service/remote/service.go
metadata/service/remote/service_test.go
protocol/dubbo/dubbo_exporter.go
protocol/dubbo/dubbo_invoker_test.go
protocol/dubbo/impl/hessian.go
protocol/grpc/grpc_exporter.go
protocol/jsonrpc/http_test.go
protocol/jsonrpc/jsonrpc_exporter.go
protocol/jsonrpc/jsonrpc_invoker_test.go
protocol/rest/rest_exporter.go
protocol/rest/rest_invoker_test.go
protocol/rest/rest_protocol_test.go
protocol/rest/server/rest_server.go
remoting/getty/getty_client_test.go

* Add two PR for bug fix.
* `1.5` has included #945 , so not in this  PR. 
Fixes #
```release-note
```

Ready for release 1.5.5

---

common/constant/key.go
config/service_config.go

it is particularly useful with a config-post-processor
Introduce a export flag to align with java implementation. It is particularly useful when a config post processor decides to break the exporting process.
Fixes #
```release-note
```

introduce a export flag to decide if a service should be export 

---

.github/workflows/github-actions.yml
cluster/router/chain/chain_test.go
config_center/apollo/impl.go
protocol/dubbo/dubbo_codec.go
protocol/dubbo/hessian2/hessian_dubbo.go
protocol/dubbo/hessian2/hessian_request.go
protocol/grpc/protoc-gen-dubbo/main.go
protocol/jsonrpc/http.go
registry/zookeeper/registry.go
registry/zookeeper/service_discovery_test.go
remoting/getty/dubbo_codec_for_test.go
remoting/getty/getty_client.go
remoting/getty/listener.go
remoting/getty/pool.go
remoting/zookeeper/client.go
remoting/zookeeper/client_test.go
remoting/zookeeper/listener.go

fix client error message
Fixes #972
```release-note
```

Fix: change client error message of issue #972

---

go.mod
go.sum

upgrade hessian2 to v1.8.1
- fix get wrong javaclassname for POJO struct. [#247](https://github.com/apache/dubbo-go-hessian2/pull/247)
- fix not enough buf error when decode date. [#249](https://github.com/apache/dubbo-go-hessian2/pull/249)
- fix emoji decoding error. [#254](https://github.com/apache/dubbo-go-hessian2/pull/254)

upgrade hessian2 to v1.8.1 which fix emoji decoding error

---

.github/workflows/github-actions.yml
integrate_test.sh

Fix: integration test in Github action

---

registry/etcdv3/listener.go
registry/etcdv3/registry.go
remoting/etcdv3/listener.go

Fix issue #951 
Fixes #
```release-note
```

Fix: issue #951 etcd exit panic

---

go.mod
go.sum
protocol/protocolwrapper/protocol_filter_wrapper.go
remoting/getty/getty_client.go

when connect to provider fail, buildInvokerChain function will occur panic
This Pr can fix #1014

FIX:when connect to provider fail, will occur panic

---

protocol/dubbo/dubbo_invoker.go

远程调用次数变量读取未使用原子操作
What this PR does:
修订远程调用次数读未使用原子操作
Which issue(s) this PR fixes:
Fixes #1025
```release-note
```

远程调用次数变量读取未使用原子操作

---

common/logger/logger.go
config/config_loader.go

Add feature :
Developers can add command line parameters when starting the program to set the location of log, provider, consumer and router configuration files.
If no parameters are added at startup, it will be read from the default environment variables **same as before**.
If you set environment variables and add parameters at startup, it will run according to the startup parameters.
Fixes #
+ In https://github.com/dubbogo/dubbo-samples/dubbo-samples/golang/helloworld/dubbo/go-server/app
You can start server width out setting environment variables, like this:
```shell
go run . -proConf ../profiles/dev/server.yml -logConf ../profiles/dev/log.yml
```
In …

Ftr: read configuration path from the command line when start

---

common/proxy/proxy.go

Ftr: Add Prox ImplementFunc to allow override impl 
重构Proxy，添加ImplementFunc函数，允许项目对Proxy的代理实现进行重新实现。
Fixes #
在网关泛调用场景下，当前GenericService实现需要修改对返回数据的处理逻辑。
目前ProxyFactory允许自定义注册，但其创建的proxy.Proxy无法重新实现。
```release-note
Ftr: Add Proxy ImplementFunc to allow override impl 
```

Refactor Proxy with ImplementFunc to allow override impl

---

README.md
README_CN.md
protocol/dubbo/dubbo_invoker.go
protocol/grpc/grpc_invoker.go
protocol/invoker.go
protocol/invoker_test.go
registry/nacos/listener.go
registry/nacos/registry.go

fix bug: protocol/dubbo/dubbo_invoker.go:DubboInvoker.reqNum should be a atomic number

Imp: destroy invoker smoothly

---

registry/nacos/registry.go

fix:nacos service provider does not require subscribe

---

config_center/zookeeper/listener.go
config_center/zookeeper/listener_test.go

Fixes #1065 
```release-note
```

Fix: fix zk listener func pathToKey

---

common/config/environment.go
common/config/environment_test.go
config/base_config.go
config/base_config_test.go
config/config_center_config.go
config/config_loader.go
config/consumer_config.go
config/provider_config.go

- Fix update of external config map
- AppExternalConfiguration orders before ExternalConfiguration
- Add config cache file
- Fix some typos
Fixes #729 
```release-note
```

Improve config center

---

go.mod
go.sum

修复客户端获取不到invokers问题 https://github.com/nacos-group/nacos-sdk-go/pull/196

up:nacos sdk version

---

config/config_api_test.go

go map在迭代的时候添加顺序和遍历顺序是不能保证一致的，因此修改了测试用例

fix:map iteration order

---

registry/zookeeper/registry.go

fix stop the provider app panic error 
Fixes #
```release-note
```

fix panic: sync: negative WaitGroup counter

---

config/config_loader.go
registry/protocol/protocol.go
registry/protocol/protocol_test.go

修改 protocol.go 文件中 getCacheKey 函数实现；
在 registryProtocol 的 reExport 函数中增加 ServiceMap.Register 操作。
- 修复issue #894 配置中心下发配置无法实时生效
- 修复多次配置更改，实时生效时，reExport 操作的Error [DubboExporter.Unexport] error: no services for dubbo 问题
- 旧的 getCacheKey 函数根据url中所有参数生成key，精度太高，url稍微有变化就生成不同的key，导致配置下发时根据providerUrl生成的key和Export存储时用的key不同，无法进行配置更新。
- Export 时使用 OverrideUrl 修改后的 providerUrl 生成key，应该使用 invoker 中最原始的 providerUrl 生成 key
```
// 初始化时
func (proto *registryProtocol) Export(invoker protocol.Invoker) protocol.Exporter {
.....
providerUrl := getProviderUrl(invoker) // 1 clone了一份url，所以修改不会影响原url
.....
proto.providerConfigurationListener.OverrideUrl(providerUrl)
.....
serviceConfigurationListener.OverrideUrl(providerUrl)
// 2 上述两个OverrideUrl修改了providerUrl的值
.....
key := getCacheKey(providerUrl) …
```

3.0 fix reExporter bug when config-center {applicationName}.configurator data change

---

common/url.go
registry/directory/directory.go
registry/event.go

Fixes #1141
```release-note
```

Fix:delete a service provider when using k8s hpa (3.0)

---

metadata/service/inmemory/service.go
registry/nacos/service_discovery.go

fix issue-1165 , remove double-check when reading ServiceDiscovery instanceMap
Fixes #1165 
NONE

modify map use in nacos service_discovery; Fix issue-1165

---

README.md
README_CN.md
cluster/cluster_impl/failback_cluster_invoker.go
common/constant/default.go
config/config_loader.go
config_center/zookeeper/impl_test.go
config_center/zookeeper/listener_test.go
go.mod
go.sum
metadata/report/etcd/report_test.go
metadata/report/zookeeper/report_test.go
registry/etcdv3/listener_test.go
registry/etcdv3/registry.go
registry/nacos/service_discovery_test.go
registry/zookeeper/service_discovery_test.go
remoting/etcdv3/listener.go
remoting/etcdv3/listener_test.go

Zookeeper client can not be connect to server in some tests.

add retry times in zookeeper starting

---

cluster/cluster_impl/base_cluster_invoker.go
cluster/cluster_impl/broadcast_cluster.go
cluster/cluster_impl/failback_cluster.go
cluster/cluster_impl/failfast_cluster.go
cluster/cluster_impl/failover_cluster.go
cluster/cluster_impl/failsafe_cluster.go
cluster/cluster_impl/forking_cluster.go
cluster/cluster_impl/interceptor_invoker.go
cluster/cluster_impl/mock_cluster.go
cluster/cluster_impl/zone_aware_cluster.go
cluster/cluster_impl/zone_aware_cluster_interceptor.go
cluster/cluster_impl/zone_aware_cluster_invoker.go
cluster/cluster_interceptor.go
common/extension/cluster_interceptor.go

make cluster interceptor a chain so that user has chance to customize cluster interceptor. also see PR #1206 for v1.5
Fixes #
```release-note
```

make cluster interceptor a chain

---

protocol/grpc/server.go
test/integrate/dubbo/go-client/go.mod
test/integrate/dubbo/go-client/go.sum
test/integrate/dubbo/go-server/go.mod
test/integrate/dubbo/go-server/go.sum
tools/cli/example/server/go.mod
tools/cli/example/server/go.sum

add grpc server reflection register logic
Fixes #1215
增加grpc server的reflection.Register逻辑，为grpcurl调试工具提供支持。
开发者需要注意，在使用grpcurl调试的过程中，传递的`接口名/方法名`需要与编译后的pb.go文件内一致，并非Dubbo-go框架配置中的InterfaceName，对于这个InterfaceName，框架只用于进行服务注册发现，网络请求逻辑还是走的grpc，也就是.pb.go文件内的`接口名/方法名`
```release-note
```

ftr: add grpc server reflection register logic

---

cluster/router/utils/bitmap_util.go
cluster/router/utils/bitmap_util_test.go
go.mod
go.sum
registry/directory/directory.go

fix https://github.com/apache/dubbo-go/issues/1214
Fixes #
```release-note
```

fix: #1214 - go race detect

---

cluster/directory.go
registry/directory/directory.go

fix: #1214 - go race detect (#1220)
Fixes #
```release-note
```

fix: #1214 - go race detect (#1220)

---

remoting/zookeeper/listener.go

treat all zk child path url as new child
Fixes #1166

fix issue 1166: treat all zk child path url as new child

---

protocol/grpc/client.go
protocol/grpc/grpc_protocol.go
protocol/grpc/protoc-gen-dubbo/examples/Makefile
protocol/grpc/protoc-gen-dubbo/examples/helloworld.pb.go
protocol/grpc/protoc-gen-dubbo/examples/helloworld.proto
protocol/grpc/server.go

- remove reflect for `SetProxyImpl` in grpc server
- update protobuf
```release-note
NONE
```

remove reflect in grpc server

---

.github/workflows/github-actions.yml
integrate_test.sh

Adding integration tests using dubbo-go-samples
Fixes #
```release-note
NONE
```

Ftr: Adding integration tests using dubbo-go-samples

---

common/metadata_info.go
test/integrate/dubbo/go-client/go.sum
test/integrate/dubbo/go-server/go.sum
tools/cli/example/server/go.sum

之前的情况会导致local模式的应用级服务发现失败，因为在local模式服务自省过程中传递的结构体common.MetadataInfo存在无法通过hessian2序列化的atomic.Bool结构，经过修改后即可。且该字段只在服务暴露时写入一次，无需使用原子操作。
Fixes #
```release-note
```

Fix: metadata info change

---

common/extension/metadata_remote.go
config/config_loader.go
config/reference_config.go
config/service_config.go
metadata/service/remoting/service.go
metadata/service/remoting/service_test.go
metadata/service/remoting_service.go
registry/event/service_instances_changed_listener_impl.go

Restructuring RemotingMetadataService to enhance the readability.
Fixes #
```release-note
NONE
```

Rft: Restructuring remoting metadata service

---

registry/zookeeper/service_discovery_test.go
remoting/zookeeper/listener.go

- fix dead lock when listener has been added to `pathMap`.
- integrate unit tests for `registry/zookeeper/service_discovery_test.go` that are dependent on `zk.TestCluster`
Fixes #1233
```release-note
NONE
```

Fix: Dead lock when zkListener is added duplicately

---

registry/zookeeper/service_discovery_test.go
remoting/getty/getty_client_test.go
remoting/zookeeper/listener.go

- fix assertion bug for asynchronous test for getty
Fixes #1233 
```release-note
NONE
```

Fix: assertion bug for asynchronous test for getty

---

config/graceful_shutdown.go
config/graceful_shutdown_config.go
filter/filter_impl/graceful_shutdown_filter.go
registry/protocol/protocol.go
registry/zookeeper/registry.go
registry/zookeeper/service_discovery.go
remoting/zookeeper/curator_discovery/service_discovery.go

- Cancel calling exporter.Unexport() in registryProtocol.Destory()
- Close zkListener before closing zkClient
- Fix timeout logic for graceful shutdown
- Fix bug that RequestsFinished always be true
- Fix bug that RejectRequest not works
Fixes #
```release-note
NONE
```

Fix: Graceful shutdown bugs

---

registry/zookeeper/service_discovery_test.go
remoting/getty/getty_client_test.go
remoting/zookeeper/listener.go

- Treat all zk child path url as new child, see also #1225, #1233
Fixes #1166
```release-note
NONE
```

Fix #1166 for 3.0: Treat all zk child path url as new child

---

cluster/directory/base_directory.go
cluster/router/chain.go
cluster/router/chain/chain.go

Fixes #
```release-note
when run NewBaseDirectory() start a new goroutine to run RouterChain Loop
```

Fix: add listen routerChain when NewBaseDirectory

---

registry/zookeeper/registry.go
registry/zookeeper/service_discovery.go

Change zkname from default to url.Location, which is more clear to define the zk client. The old way would let different directories with different zk location to have same zk client, which will caust bugs in 1.5 and 3.0 's multy-zone samples.
Fixes #
```release-note
```

Fix/zkname 

---

cluster/router/v3router/judger/attachment_match_judger.go
cluster/router/v3router/judger/attachment_match_judger_test.go
cluster/router/v3router/judger/list_string_match_judger_test.go
cluster/router/v3router/judger/method_match_judger.go
cluster/router/v3router/judger/method_match_judger_test.go
cluster/router/v3router/judger/url_label_match_judge_test.go
cluster/router/v3router/router_chain.go
cluster/router/v3router/router_chain_test.go
config/uniform_router_config.go
metadata/report/etcd/report.go

make the package v3router/judger test coverage rate reach 80%

---

remoting/zookeeper/listener.go

Fixes #1274
```release-note
```

Fix: when zk remoting.EventTypeAdd event send fail, need delete the path from zk listener pathmap

---

registry/directory/directory.go
registry/event.go
registry/event_test.go

Add Key Func in ServiceEvent, so that the developer can extend the Key generate method.

support Key Func in ServiceEvent

---

protocol/grpc/server.go
tools/cli/client/client.go

Ues time.Timer instead the time.After
```
// After waits for the duration to elapse and then sends the current time
// on the returned channel.
// It is equivalent to NewTimer(d).C.
// The underlying Timer is not recovered by the garbage collector
// until the timer fires. If efficiency is a concern, use NewTimer
// instead and call Timer.Stop if the timer is no longer needed.
func After(d Duration) <-chan Time {
return NewTimer(d).C
}
```
Fixes #
```release-note
```

performance optimization: change time.After => time.NewTimer

---

config/config_loader.go

optimize code, the original code  miss  lock

optimize: add lock

---

common/url.go

当注册中心或者元数据中心address配置为多个例如`127.0.0.1:2181,127.0.0.2:2181,127.0.0.2:2181`时
```
if strings.Contains(location, ":") {
s.Ip, s.Port, err = net.SplitHostPort(location)
if err != nil {
return &s, perrors.Errorf("net.SplitHostPort(url.Host{%s}), error{%v}", s.Location, err)
}
break
}
```
net.SplitHostPort(location) 方法解析会报错too many colons in address，所以url中的host和port取第一个即可
Provider starts metadata report error, and the error is {Start MetadataReport failed.: Invalid MetadataReportConfig.}

url  too many colons in address

---

registry/directory/directory.go
registry/event.go
registry/event_test.go

Add Key Func in ServiceEvent, so that the developer can extend the Key generate method.

Support Key generate Func in ServiceEvent

---

config/config_loader.go

Revert "optimize: add lock"

---

common/rpc_service.go
config/config_center_config.go
config/config_loader.go
config/provider_config.go
config/reference_config.go
remoting/zookeeper/listener.go

Fixes #1320 
Fixes #1325 
增加了generic client 必要的启动逻辑，确保不会panic
修改配置中心初始化时错误的日志为warning
```release-note
```

fix: #1320 泛化调用+应用级服务发现，客户端 panic

---

go.mod
go.sum
registry/etcdv3/listener.go
registry/kubernetes/listener.go
registry/nacos/listener.go
registry/zookeeper/listener.go

refer to #1314 
Fixes #
```release-note
```

fix: change register event chan to unbundent chan

---

common/constant/default.go
config/config_loader.go
config/config_loader_test.go
config/reference_config.go

Fixes #1323 
```release-note
```

fix: #1323 delete zk registry when set defualt consumer/provider config

---

config/config_loader.go

- Decrease logging level from warn to debug when providerConfig or consumerConfig is not specified
Fixes #
```release-note
NONE
```

Fix: Decrease logging level when config is not specified

---

registry/nacos/registry.go

Fixes #1331
```release-note
```

Ftr: Change ServiceName like Java Style on Nacos

---

cluster/router/tag/router_rule.go
filter/filter_impl/generic_filter.go
filter/filter_impl/generic_filter_test.go
filter/filter_impl/generic_service_filter.go

- Fix: `struct2mapAll` couldn't handle with complicated struct.(same with #1354)
- Fix: Size computation for allocation may overflow
Fixes #
```release-note
```

Fix: struct2MapAll logics

---

cluster/loadbalance/consistent_hash.go
cluster/loadbalance/consistent_hash_test.go
go.mod
go.sum
registry/event/protocol_ports_metadata_customizer.go
remoting/etcdv3/client.go

Fix: ut, replace, hash problem

---

go.mod
go.sum
registry/nacos/service_discovery.go

Add nacos group  to subscribe param of service disc to avoid  the error  log of subscribition empty host.
Fixes #
```release-note
```

fix: nacos service disc error log bug

---

remoting/getty/config.go

Fixes #1362
```release-note
None
```

Fix: fix the exception when tcp timeout is less than 1s for 3.0 #1362

---

common/logger/logger.go

修复其他模块在 init 时使用 logger 模块 panic 的问题 
https://github.com/apache/dubbo-go/commit/299cac426f9bd8415e925e0b23f26d4079bd924f#r55820216

fix logger panic

---

config/config_loader.go
imports/imports.go

This PR recovers the call of `remoteMetadataService.PublishMetadata` in `registerServiceInstance()`, so the providers could publish the app level metadata to the remote metadata report.

Fix: app level metadata bug

---

config/config_center_config.go
config_center/dynamic_configuration.go

This API can create dynamic configuration from centerConfig generated by config api.
This gives developers more flexibility to use a particular dubbogo feature module.
After this PR, we can use use configuration api in this way:
```go
dynamicConfig, err := config.NewConfigCenterConfig(
config.WithConfigCenterProtocol("zookeeper"),
config.WithConfigCenterAddress("127.0.0.1:2181")).GetDynamicConfiguration()
if err != nil{
panic(err)
}
if err := dynamicConfig.PublishConfig("dubbo-go-samples-configcenter-zookeeper-client","dubbogo", `## set in config center, group is 'dubbo', dataid is 'dubbo-go-samples-configcenter-nacos-client', namespace is default
dubbo:
registries:
"demoZK":
protocol: "nacos"
timeout: "3s"
address: "127.0.0.1:8848"
consumer:
registry:
- demoZK
references:
"greeterImpl": …
```

fix: add get dynamic configuration api

---

config/config_center_config.go
config/root_config.go
config_center/dynamic_configuration.go
config_center/zookeeper/impl.go

Find out the problem that zk can't store \n charactor correctly, which is used by config center.

store zk value with base64.

---

go.mod
go.sum

upgrade hessian2 to v1.9.3
see https://github.com/apache/dubbo-go-hessian2/releases/tag/v1.9.3
None
```release-note
- upgrade hessian2 to v1.9.3
```

upgrade hessian2 to v1.9.3

---

common/logger/logger.go
common/logger/logging.go
config/logger_config_test.go
go.mod
go.sum

* Logger 接口添加 fatal 和 fatalf 方法
* 由于 zap 的 fatal 方法会调用 os.Exit 因此导入了 "bou.ke/monkey" 包用于测试 fatal，防止因执行 logger.Fatal 导致单测 ci 失败

Ftr: add fatal method for logger(config-enhance branch)

---

config/application_config.go
config/config_loader.go
config/consumer_config.go
config/dubbo_bootstrap.go
config/graceful_shutdown_config.go
config/logger_config.go
config/metadata_report_config.go
config/metric_config.go
config/protocol_config.go
config/provider_config.go
config/registry_config.go
config/remote_config.go
config/root_config.go
config/router_config.go
config/service_config.go
config/service_discovery_config.go
go.sum
remoting/nacos/builder_test.go

feat(config): add root config api builder

---

cluster/router/v3router/router_chain.go
config/config_center_config.go
config_center/apollo/impl.go
config_center/dynamic_configuration.go
config_center/file/impl.go
config_center/nacos/impl.go
config_center/zookeeper/impl.go
config_center/zookeeper/listener.go
remoting/zookeeper/listener.go

1. fix the startup process of the configuration center(remove error log)
2. refactor zk registry listener
Fixes #
```release-note
```

[#1559]: adjust the startup process of the configuration center

---

config/config_loader.go
config/config_loader_options.go
config/config_loader_options_test.go
config/root_config.go

fix: #1558: Set root config to global ptr in Init() function.

---

filter/gshutdown/filter.go

[fix] graceful shutdwon filter

---

protocol/dubbo/impl/hessian.go

hessian encode attachments return error
Fixes #
```release-note
```

hessian encode attachments return error

---

go.mod
go.sum

upgrade hessian to v1.9.5
see:
- https://github.com/apache/dubbo-go-hessian2/releases/tag/v1.9.4
- https://github.com/apache/dubbo-go-hessian2/releases/tag/v1.9.5
```release-note
- upgrade hessian to v1.9.5
```

upgrade hessian to v1.9.5

---

config_center/zookeeper/impl.go
go.mod
go.sum
registry/zookeeper/registry.go
remoting/zookeeper/listener.go

1. remove CLEAR label;
2. remove register/unregister logic for watch children;
3. reorder the zk dynamic configuration code
4. adapt the gost
Fixes #
```release-note
```

refactor listenDirEvent

---

registry/nacos/registry.go

- nacos registry servicce  provider's url methods key is empty now, and is used by pixiu-gateway

fix: add nacos methods key

---

config/service_config.go

As for java client, if user set 'version' to '1.0.0" and doesn't set 'group' key. the reference url's param contains version=1.0.0 and doesn't contain 'group' key.
But golang server regster 'group' key with "" value even if user didn't configure service's 'group' field in config file.
That's a bug. I open this pr is to let url to be register, doesn't contain group or value key, if user didn't set.

fix:  service register url's group and version key with "" value.

---

config/config_loader.go
config/instance/registry_metadata_report.go
config/instance/registry_metadata_report_test.go
config/metadata_report_config.go
config/registry_config.go
config/service_config.go
metadata/mapping/metadata/service_name_mapping.go
metadata/report/etcd/report.go
metadata/report/nacos/report.go
metadata/report/zookeeper/report.go

local mode, metadata mapping is reported using registration information
Fixes https://github.com/apache/dubbo-go/issues/1610
```release-note
```

metadata mapping reported using registry config

---

protocol/dubbo3/internal/server.go
protocol/grpc/internal/helloworld/server.go
protocol/grpc/internal/routeguide/client.go
protocol/grpc/internal/routeguide/server.go

Some code in the project uses native log, such as :
```go
import (
"log"
)
log.Printf("xxx")
```
Now change it to the unified use of the framework itself logger, the code is in `common/logger` ，the modified method of use is: 
```go
import (
log "dubbo.apache.org/dubbo-go/v3/common/logger"
)
log.Infof("xxx")
```

Ftr: change log to dubbo go logger

---

config/config_center_config.go
config/config_loader_options.go
config/config_loader_options_test.go

配置中心支持自定义文件类型解析器，目前支持`json`、`yaml`、`properties`、`yml`、`toml`五种文件类型配置
Fixes #
```release-note
```

add:support file extension

---

protocol/dubbo/dubbo_protocol.go

- fix issus where RPCResult.Attrs is not sent
Fixes #
```release-note
```

fix(dubbo): fix issus where result.attrs is not sent

---

protocol/dubbo/impl/hessian.go

Unmarshal request body by `hession.go` , the attribute `attachments` maybe nil or empty string, and will stop the invoked
if attachments nil or empty string , default a value that for normal invoking
Fixes #1583 
```release-note
```

Fix: attachments maybe nil or empty string

---

cluster/cluster/base/cluster_invoker.go
cluster/cluster/failback/cluster_invoker.go
cluster/cluster/failsafe/cluster_invoker.go
cluster/directory/base/directory_test.go
common/constant/default.go
config_center/configurator/override.go
config_center/parser/configuration_parser.go
registry/zookeeper/listener.go
remoting/zookeeper/client.go
remoting/zookeeper/listener.go

avoid the problem of cpu idling & fix wrong definition of error

---

config/config_center_config.go
config_center/nacos/impl.go
metadata/report/nacos/report.go

The user name and password of nacos are obtained from the configuration, not from param
Fixes #
```release-note
```

unified nacos user and password obtaining path

---

protocol/dubbo/impl/hessian.go
protocol/dubbo/impl/hessian_test.go

hessian2 supports setting the type of Java method parameters
Fixes https://github.com/apache/dubbo-go/issues/1624
```release-note
```

hessian2 supports setting the type of Java method parameters

---

remoting/nacos/builder.go
remoting/nacos/builder_test.go

support set nacos context path
Fixes #https://github.com/apache/dubbo-go/issues/1653
```release-note
registries:
"demoNacos":
protocol: "nacos"
timeout	: "3s"
address: "127.0.0.1:8848" or. "127.0.0.1:8848/nacos"
```

3.0 support set nacos ContextPath

---

remoting/nacos/builder.go
remoting/nacos/builder_test.go

support set nacos context path
Fixes #https://github.com/apache/dubbo-go/issues/1653
```release-note
registries:
"demoNacos":
protocol: "nacos"
timeout	: "3s"
address: "127.0.0.1:8848" or. "127.0.0.1:8848/nacos"
```

1.5 support nacos ContextPath

---

cluster/cluster/base/cluster_invoker.go
cluster/cluster/failfast/cluster_invoker.go
cluster/cluster/failover/cluster_invoker.go
cluster/cluster/forking/cluster_invoker.go
cluster/cluster/zoneaware/cluster_invoker.go
common/constant/default.go
filter/generic/service_filter.go
filter/generic/util.go
protocol/invocation.go
protocol/invocation/rpcinvocation.go

support $invokeAsync

---

registry/polaris/registry.go
registry/polaris/service_discovery.go

Fixes #1687 
```release-note
```

[ISSUE #1687] Fix the problem that the heartbeat cannot be reported

---

cluster/router/v3router/router_chain.go
common/constant/default.go
common/constant/key.go
config/consumer_config.go
config_center/zookeeper/impl.go
config_center/zookeeper/listener.go
remoting/listener.go
remoting/zookeeper/client.go
remoting/zookeeper/listener.go

refactor zk dynamic configuration listener

---

cluster/cluster/adaptivesvc/cluster_invoker.go
cluster/cluster/zoneaware/cluster_interceptor.go
cluster/cluster/zoneaware/cluster_invoker.go
cluster/cluster/zoneaware/cluster_invoker_test.go
common/proxy/proxy.go
common/proxy/proxy_factory/default.go
common/proxy/proxy_factory/pass_through.go
filter/active/filter.go
filter/active/filter_test.go
filter/adaptivesvc/filter.go
filter/auth/default_authenticator.go
filter/auth/default_authenticator_test.go
filter/generic/filter.go
filter/generic/filter_test.go
filter/generic/service_filter.go
filter/seata/filter.go
protocol/dubbo/dubbo_codec.go
protocol/dubbo/dubbo_invoker.go
protocol/dubbo/dubbo_invoker_test.go
protocol/dubbo3/dubbo3_invoker.go
protocol/invocation.go
protocol/invocation/rpcinvocation.go
protocol/result.go
remoting/getty/dubbo_codec_for_test.go
remoting/getty/getty_client_test.go

-  refactor invocation interface, it's divided into two parts: attachments and attributes
- Attachments
- SetAttachment
- GetAttachment
- GetAttachmentInterface
- GetAttachmentWithDefaultValue
- Attributes
- SetAttribute
- GetAttribute
- GetAttributeWithDefaultValue
Fixes #
```release-note
```

refactor: invocation interface

---

protocol/jsonrpc/jsonrpc_protocol.go

**What this PR does**: make the jsonrpc protocol request timeout can be read from consumer config . The read order of requestTimeout is from url , if nil then from consumer config , if nil then default 3s. requestTimeout can be dynamically updated from config center.
Fixes #1584

refactor json rpc request timeout

---

protocol/dubbo/dubbo_protocol_test.go
protocol/dubbo3/dubbo3_invoker.go
registry/nacos/service_discovery_test.go

Fixes #
```release-note
add some unit test
```

add unit test

---

cluster/cluster/adaptivesvc/cluster_invoker.go
cluster/utils/adaptivesvc.go
filter/adaptivesvc/filter.go

- fix issue where the updater not found when reaching the limitation
- add an util for detecting the error reaching the limitation
Fixes #

fix: fix adaptive service issues

---

go.mod
go.sum
protocol/dubbo/hessian2/hessian_dubbo_test.go
protocol/dubbo/hessian2/hessian_response.go

upgrade hessian2 to v1.11.0, see https://github.com/apache/dubbo-go-hessian2/releases/tag/v1.11.0
None

upgrade hessian2 to v1.11.0

---

go.mod
go.sum

现在有两种 Panic 的问题被修复了，主要是因为连接中断导致 Connection 这个对象被清理了，然后有其他协程内会执行 Connection 这个对象就会出现 Panic 的问题。
- 当连接中断的时候，Getty 会收到一个 EOF Error，接着 defer 会执行 gc() 函数，他会把 Connection 设置为 nil。但是有很多个 Task 被放到了 Pool 里面，等待 Pool 调度到 Task 的时候，他会开启协程去执行 Task。这时候 Connection 已经被设置为空了，那么用到 Connection 的函数就会出现 panic 的问题。
- 在 Dubbo go 中会执行 GetActive 这个函数，GetActive 也是操作 Connection 内的函数，但是其实那时候可能因为上层的超时或者解析失败已经连接中断，那么 Connection 已经被清除了，所以就出现了 Panic 的问题。
Fixes #

Imp: upgrade getty from 1.4.7-rc2 to 1.4.7

---

common/logger/logger.go

`config.ZapConfig.Build(zap.AddCallerSkip(1))` This is not correct, the log does not print the caller
add zap.AddCaller() turn on the print caller switch.
Fixes #

zap log addCaller

---

common/constant/default.go
config/provider_config.go
config/service_config.go

fix(adasvc): do not load adaptive service filter if not set

---

go.mod
go.sum

Fixes https://github.com/apache/dubbo-go-samples/issues/315

Update grpc-go to support triple stream ctx attachement

---

registry/directory/directory.go
registry/directory/directory_test.go

refine RegistryDirectory. toGroupInvokers func
Fixes #

directory refine

---

config/graceful_shutdown.go
config/graceful_shutdown_config.go
config/root_config.go
filter/graceful_shutdown/consumer_filter.go
filter/graceful_shutdown/provider_filter.go
registry/protocol/protocol.go

refine graceful pr:https://github.com/apache/dubbo-go/pull/1675
Fixes #

graceful pr refine

---

config/graceful_shutdown_config.go
config/graceful_shutdown_config_test.go
filter/graceful_shutdown/procider_filter_test.go
filter/graceful_shutdown/provider_filter.go

The PR #1731 wants to use atomic package, but forgot to change the type of the RejectRequest, this PR fixed this problem.
Fixes #1731

fix(config): fix the type of reject request

---

cluster/cluster/adaptivesvc/cluster_invoker.go
common/constant/key.go
filter/adaptivesvc/filter.go

fix(adasvc): do not use adaptive service filter if disabled on the client side

---

CHANGELOG.md

Release 3.0.1 CHANGELOG
Fixes #

Release 3.0.1 CHANGELOG

---

common/constant/key.go
config/config_loader.go
config/config_loader_options.go
config/config_loader_options_test.go
config/profiles_config.go
config/profiles_config_test.go
config/root_config.go
config/testdata/config/active/application-local.yaml
config/testdata/config/active/application.yaml

主要逻辑是根据`dubbogo.yaml`文件里面配置的`dubbo.profiles.active`值合并文件
例如:在`dubbogo.yaml`文件里面配置了`dubbo.profiles.active=local`则会合并`dubbogo.yaml`和`dubbogo-local.yaml`两个配置文件里面的内容。
但是如果你通过命令`export DUBBO_GO_CONFIG_PATH= PATH_TO_SAMPLES/helloworld/go-server/conf/application.yaml`则会合并`application.yaml`和`application-local.yaml`两个文件
> 出现重复值按照`active`里面的为最终结果
例如：在`dubbogo.yaml`里面配置`dubbo.registries.nacos.timeout=3s`在`dubbogo-local.yaml`里面配置值是`10s`,最终`dubbo.registries.nacos.timeout=10s`
Fixes #

config merge

---

go.mod
go.sum
remoting/zookeeper/listener.go

feat(gost): upgrade gost dependency version and remove redundant code

---

.github/workflows/github-actions.yml
.github/workflows/golangci-lint.yml

切换到官方的 lint，可跳过 unused 的校验
Fixes #

feat: change lint to official lint

---

config/consumer_config.go

解决consumer和provider同时存在的时候启动异常
Fixes #
https://github.com/apache/dubbo-go/issues/1764

fix: fix unexpected error when provider and consumer exist together

---

.github/workflows/github-actions.yml

Merge develop branch to 3.0 before running ci.
Some errors occurs that when two developers run ci in there pr, they all passed. But error occurs after the two prs merged, because ci only check the developer's branch, but NOT the branch after merged to base(3.0).
This pr Add `Merge Base` ci procedure, to merge develop branch to base(3.0) before running ci.

fix: github action

---

protocol/dubbo/impl/hessian.go

Fixes https://github.com/apache/dubbo-go/issues/1782
- [] Your new-created file needs to have [apache license](https://raw.githubusercontent.com/dubbogo/resources/master/tools/license/license.txt) at the top, like other existed file does.

support java method param java.lang

---

cluster/loadbalance/p2c/loadbalance.go
filter/adaptivesvc/limiter/hill_climbing.go
filter/adaptivesvc/limiter/limiter.go
filter/adaptivesvc/limiter/utils.go

- concurrency is renamed to maxCapacity
- fix the way calculating the value of maxCapacity
- limitation is not updated as expectation
Fixes #

fix(adasvc): fix issue where limitation not updates

---

config/root_config.go
remoting/getty/config.go

1.When init of rootConfig is used, `var rootConfig` is not configured. This variable is default by default, rootConfig parameter should be given after init，If this is not done, `GetRootConfig()` will not get the correct value.
2. The `GettySessionParam` serialization alias is missing, which causes the content to not be configured.
Fixes #
Fixed that`GetRootConfig() `could not get parameters correctly
Fixed that `GettySessionParam` could not be serialized correctly

fix RootConfig and getty-session-param

---

cluster/cluster/adaptivesvc/cluster_invoker.go
filter/adaptivesvc/filter.go
protocol/invocation/rpcinvocation.go

- fix getting attachment issue for triple
Fixes #

fix(adasvc): fix getting attachment issues for triple

---

config/config_loader_options.go
config/metric_config.go
config/reference_config.go
imports/imports.go

1. Fix MetricsConfig's Enable type string to bool, default enable.
2. Add `func (pcb *ReferenceConfigBuilder) SetURL(url string) ` to *ReferenceConfigBuilder
3. Add default tps limiter and strategy to import/imports.go

Fix: bugfix of metrics and config

---

registry/base_registry.go

`Len (c.ip) > 0` should be given `c.ip` instead of `localIp`
Fixes # IP can be normally exposed according to environmental variables

fix(register): fix ip register issue

---

.github/workflows/codeql-analysis.yml
.github/workflows/github-actions.yml
.github/workflows/golangci-lint.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

Set permissions for GitHub actions

---

protocol/dubbo/impl/codec.go
remoting/getty/readwriter_test.go

fix: fix unit test

---

README.md
README_CN.md
protocol/dubbo/dubbo_codec.go
protocol/dubbo/impl/codec.go
protocol/dubbo/impl/const.go
remoting/codec.go
remoting/getty/dubbo_codec_for_test.go
remoting/getty/listener.go
remoting/getty/readwriter.go

the current dubbo-go do not follow the getty rule when decoding tcp network streams
Fixes #

Fix: decode net stream bytes as getty rule

---

remoting/getty/listener.go

Add req.Data to OnMessage panic error log

---

protocol/dubbo/hessian2/hessian_request.go
protocol/dubbo/hessian2/hessian_response.go
protocol/dubbo/impl/codec.go
remoting/getty/readwriter.go

* Dubbo recommand package data length not greater than 8MiB.
* If package data length greater than 8MiB, generate warnning.
* If package data lenght greater than user's config, generate exception.
Signed-off-by: stonex <1479765922@qq.com>
Fixes #1839 

fix: limit rpc package data size by user's config rather than DEFAULT_LEN.

---

config/metric_config.go
metrics/prometheus/reporter.go
metrics/reporter.go

Signed-off-by: jyz0309 <45495947@qq.com>
Change metric type to observe RT P99 value.
None.

Use summary type to observe p99

---

cluster/loadbalance/leastactive/loadbalance.go

feat: leastActiveLoadBalance code optimization, according to dubbo-java optimization records. For example:
https://github.com/apache/dubbo/pull/2962
https://github.com/apache/dubbo/pull/5909
Fixes #

feat: Optimized load balancing algorithm

---

.github/workflows/github-actions.yml
common/proxy/proxy_factory/default.go
common/proxy/proxy_factory/pass_through.go
common/proxy/proxy_factory/utils.go
remoting/getty/listener.go

Signed-off-by: stonex <1479765922@qq.com>
+ Dubbo3.0 and grpc based service in dubbo-golang will crash if user throw exception in their code, only getty based protocol catch these exception in method `OnMessage`.
+ Catch user's exception in `Invoke` to prevent the server from hanging up due to the exception .

fix: complete grpc based protocol panic recover handle.

---

cluster/loadbalance/random/loadbalance.go

feat: RandomLoadBalance code optimization, update that how to judge the same weight.about 
https://github.com/apache/dubbo/pull/6479

feat: RandomLoadBalance code optimization

---

filter/hystrix/filter.go

I tested the problem mentioned in [#1883](https://github.com/apache/dubbo-go/issues/1883). When I trying to set hystrix in config file, I get the type conversion problem, even though I have used it as example in the source code(https://github.com/apache/dubbo-go/blob/master/filter/hystrix/filter.go#L86-L126). 
- Add a type check to fix interface conversion error when parsing Hystrix filter config in yaml file.
Fixes #1883

Fix: Interface conversion when parsing Hystrix filter config in yaml file (#1883)

---

protocol/dubbo/impl/hessian.go

Fix: export method getArgsTypeList for extension

---

config/reference_config.go
config/service_config.go

ProviderConfig.Filter and ReferenceConfig.Filter not work. Fix them

Fix: ProviderConfig.Filter and ReferenceConfig.Filter not work

---

config/reference_config.go
remoting/xds/error.go

fix: typo correction

---

common/metadata_info.go

fix different revision calc in `service_revision_customizer.go:resolveRevision` and `metadata_info.go:(*MetadataInfo).CalcAndGetRevision`, which make client get empty server metadata.
Fixes #1925

Fix: fix revision calc

---

filter/adaptivesvc/limiter/hill_climbing.go

Whether this log is output or not, the date will be formatted and cost a lot time, now it will be output without formatting as `2022-07-06 19:37:39.4692053 +0800 CST m=+0.775520901`
Fixes #1954 

Imp: remove useless time format

---

registry/polaris/listener.go
registry/polaris/registry.go

This pr removes the consumer and watch logic in the Polaris registry.

Fix: remove consumer of polaris

---

protocol/invocation/rpcinvocation.go

RPCInvocation::GetAttributeWithDefaultValue() has a typo which couldn't
get attributes correctly, this PR fixes that issue.
Signed-off-by: Xuewei Niu <justxuewei@apache.org>
Fixes #

fix(proto): fix getting attributes issue

---

filter/sentinel/filter.go
registry/polaris/listener.go
registry/polaris/registry.go

i am write a [linter](https://github.com/alingse/asasalint) to lint bad use `pass []any as any  in variadic function` and check the top go repo.
the `AssembleMsg`  func code is here https://github.com/alibaba/sentinel-golang/blob/2af86608857884da543eabe7941b61d60edc51a4/logging/logging.go#L152-L208
```Go
func AssembleMsg(depth int, logLevel, msg string, err error, keysAndValues ...interface{}) string {
....
kvLen := len(keysAndValues)
if kvLen&1 != 0 {
sb.WriteByte(',')
sb.WriteByte('"')
sb.WriteString("kvs")
sb.WriteByte('"')
sb.WriteByte(':')
s := fmt.Sprintf("%+v", keysAndValues)
data := toSafeJSONString(s)
sb.Write(data)
} else if kvLen != 0 {
for i := 0; i < kvLen; {
k := keysAndValues[i]
v := keysAndValues[i+1]
....
```
if someone call …

Fix: fix AssembleMsg bad use, pass []any as any in variadic function

---

cluster/loadbalance/p2c/loadbalance.go
cluster/loadbalance/p2c/loadbalance_test.go
registry/servicediscovery/instance/random/random_service_instance_selector.go

Move the rand.Seed() call to init()
Fixes #1957 

Fix: fix rand.Seed() duplicate concurrent calls

---

metrics/prometheus/reporter.go

fix bug when creating metrics objects concurrently
Fixes #1953 

Fix: fix bug when creating metrics objects concurrently

---

go.mod
go.sum

gost upgrade to master of latest

---

go.mod
go.sum

- upgrade hessian2 to v1.11.1
see https://github.com/apache/dubbo-go-hessian2/releases/tag/v1.11.1

upgrade hessian2 to v1.11.1

---

config/service_config.go
filter/token/filter.go
protocol/dubbo/dubbo_exporter.go
protocol/dubbo/dubbo_invoker.go
protocol/dubbo/dubbo_protocol_test.go
protocol/dubbo3/dubbo3_exporter.go
protocol/dubbo3/dubbo3_invoker.go
protocol/dubbo3/dubbo3_protocol_test.go
protocol/grpc/grpc_exporter.go
protocol/grpc/grpc_protocol_test.go
protocol/jsonrpc/jsonrpc_exporter.go
protocol/jsonrpc/jsonrpc_protocol_test.go
protocol/protocol.go
protocol/rest/rest_exporter.go
protocol/rest/rest_protocol_test.go
registry/protocol/protocol.go
remoting/zookeeper/curator_discovery/service_discovery.go
remoting/zookeeper/listener.go

…fix some spelling mistake
fix a bug where filter was not currently working properly and fix some spelling mistake
Fixes #1988 

[#1998]fix a bug where filter was not currently working properly in triple protocol

---

config/graceful_shutdown.go
config/graceful_shutdown_config.go
config/graceful_shutdown_config_test.go

https://github.com/apache/dubbo-go/issues/1974  fix shotdown InternalSignal default value
Fixes #

Fix(#1974):fix shutdown InternalSignal default value

---

common/constant/file/suffix.go
config/config_resolver.go
config/config_resolver_test.go
config/testdata/config/resolver/application.yaml

resolve placeholder `${xxx:defaultValue}`
Fixes #1983

feat: resolve placeholder

---

registry/directory/directory.go
registry/event/service_instances_changed_listener_impl.go

Signed-off-by: xiaoxu <lexuscyborg103@gmail.com>
`Notify one after one` might have performance issues, this PR makes serviceListeners notify events concurrently and do not wait for notification complated.
I am wondering if it's needed to add a sync.WaitGroup after NotifyAll to wait notification completed or not.
Fixes https://github.com/apache/dubbo-go/issues/2030

feat: use notifyAll insteadOf notify for listener events notify

---

dubbogo-cli/README.md
dubbogo-cli/README_CN.md
dubbogo-cli/cmd/show.go
dubbogo-cli/metadata/metadata.go
dubbogo-cli/metadata/zookeeper/zookeeper.go

CLI: Support getting metadata from metadataCenter

---

config/reference_config.go

add more setter of ReferenceConfigBuilder
Fixes #2078

fix: add more setter of ReferenceConfigBuilder

---

common/constant/key.go
common/constant/polaris_key.go
filter/filter_impl/import.go
filter/polaris/limit/default.go
filter/polaris/limit/limiter.go
go.mod
go.sum
imports/imports.go
remoting/polaris/builder.go
remoting/polaris/parser/parser.go
remoting/polaris/parser/parser_test.go

[ISSUE #2123] Feat/polaris ratelimit

---

registry/servicediscovery/service_discovery_registry.go

fix  DUBBO_IP_TO_REGISTRY doesn't work
Fixes #
#2096

Fix:ENV DUBBO_IP_TO_REGISTRY doesn't work

---

registry/base_registry.go
registry/directory/directory.go
registry/etcdv3/registry.go
registry/mock_registry.go
registry/nacos/registry.go
registry/polaris/registry.go
registry/registry.go
registry/servicediscovery/service_discovery_registry.go
registry/xds/registry.go
registry/zookeeper/registry.go
registry/zookeeper/service_discovery.go

修复consumer启动时立即发起调用，出现找不到provider的相关问题。本质原因是因为在consumer启动时会“异步”订阅provider，在发起调用时有可能订阅回调事件还没有被触发，从而导致找不到provider.
修改：在异步订阅前 先同步获取provider实例。(当前pr修改了nacos和polaris，后续可以按需实现zk,etcd.)
Fixes https://github.com/apache/dubbo-go/issues/1991

3.0 notify sleep

---

config/logger_config.go
config/metric_config.go
config/root_config.go
metrics/prometheus/reporter.go

Revert "Dynamic update config for logger level & metric enable"

---

cluster/router/polaris/router.go
filter/polaris/limit/limiter.go
go.mod
go.sum
metadata/service/local/service_proxy.go
metadata/service/local_service.go
remoting/polaris/builder.go

Revert "Fix: Do not launch Polaris governance capability if Polaris is not enabled"

---

CHANGELOG.md

This pull request is for release v3.0.5, which focuses on stability. The CHANGELOG is updated.
Fixes #
Signed-off-by: Xuewei Niu <justxuewei@apache.org>

docs: Update CHANGELOG for release v3.0.5

---

common/url.go
config/metric_config.go
registry/polaris/registry.go
registry/polaris/service_discovery.go
registry/polaris/utils.go
remoting/zookeeper/listener.go

[ISSUE #2216] fix register instance protocol info to polaris when use tripe

---

tools/dubbogo-cli/cmd/show.go
tools/dubbogo-cli/go.mod
tools/dubbogo-cli/go.sum

tablewrite cli show

---

common/constant/default.go
config/protocol_config.go
config/protocol_config_test.go
config/service_config.go
config/testdata/config/protocol/application.yaml
go.mod
go.sum
protocol/dubbo3/dubbo3_invoker.go
protocol/dubbo3/dubbo3_protocol.go
protocol/grpc/client.go
protocol/grpc/client_test.go
protocol/grpc/grpc_protocol.go
protocol/grpc/server.go

According to the pr of #1654, for the client side, the function works normally, but for the server side, the order of Provider Export is not always the same, resulting in sometimes max-server-send-msg-size not taking effect, and for the server side, it is not possible to customize the message size based on the request, so a more appropriate The more appropriate setting should be placed on the protocol.
This pr also fixes the grpc protocol, which can also be used to customize the message size in this way.
Custom triple/grpc server message size
For message size , The available units are, b/kb/kib/mib/mb/gib/gb, 1kb = 1000b and 1kib = 1024b
Provider:
```yaml
dubbo:
protocols:
triple:
name: tri
port: 20000
max-server-send-msg-size: 4mib
max-server-recv-msg-size: 4mib …
```

[Bugfix] Custom triple server message size

---

config_center/nacos/impl.go
config_center/zookeeper/impl.go

Implement RemoveConfig API for nacos and zookeeper.
Fixes #2233

feat: implement RemoveConfig API for nacos and zookeeper

---

.github/workflows/github-actions.yml

[3.0] ci: Enable integration testing for push event

---

.github/workflows/github-actions.yml

Remove the 'if' condition from the Integration Testing to enable testing for push events. Additionally, this commit removes unnecessary logs of certain environment variables.
Fixes: #2295

ci: Enable integration testing for push event

---

README.md
README_CN.md

The link to cli-v2 in README is no longer valid. It has been updated to the latest path. 
Both the README and RAEDME_CN have been modified.

docs: Change the PATH of cli-v2 in README & RAEDME_CN

---

remoting/zookeeper/listener.go

When consumer starts before any provider is available, there're error messages that keep printing out on the Consumer side when subscribing/listening to the Zookeeper node.
```text
Get children of path /dubbo/xxxService/providers with watcher failed, the error is zk: node does not exist.
```

Ignore node not exist error message and continue retry

---

config/provider_config.go
config/service.go
metadata/service/local/service_proxy.go

The PR fixes the problem that the metadata invoker is destroyed too early.
Please refer to the issue for more details. Plus, this PR updates some logs
about registering services.
Fixes: #2321
Signed-off-by: Xuewei Niu <justxuewei@apache.org>

fix: The metadata invoker is destroyed too early

---

common/constant/key.go
config/metric_config.go
filter/metrics/filter.go
filter/metrics/filter_test.go
metrics/prometheus/after_invocation.go
metrics/prometheus/api.go
metrics/prometheus/before_invocation.go
metrics/prometheus/common.go
metrics/prometheus/constant.go
metrics/prometheus/metric_set.go
metrics/prometheus/reporter.go
metrics/prometheus/reporter_test.go
metrics/reporter.go

I have read the code related to the metrics module and plan to refactor the existing code before adding new metric instrumentation. This will make it easier for future development work. Could you please review the current file structure design to see if it conforms to community standards?
我阅读了 metrics 模块相关的代码，在添加新的指标埋点之前，先对已有的代码进行重构，便于后续的开发工作。请查看目前的文件结构设计是否符合社区规范？

refactor: split metrics module into multiple files

---

cluster/router/condition/dynamic_router.go
cluster/router/condition/factory.go
cluster/router/condition/matcher/attachment.go
cluster/router/condition/matcher/base.go
cluster/router/condition/matcher/factory.go
cluster/router/condition/matcher/pattern_value/scope.go
cluster/router/condition/matcher/pattern_value/wildcard.go
cluster/router/condition/route.go
cluster/router/condition/router_test.go
common/constant/key.go
common/extension/router_condition_matcher.go
common/extension/router_condition_pattern_value.go
imports/imports.go

Implement condition routing functions and complete related testing
The functions include:
(1) attachment support, scope support 
(2) dynamic routing support

add: implement dynamic routing

---

registry/polaris/service_discovery.go

try to resolve PR:https://github.com/apache/dubbo-go/pull/2314 polaris panic error

fix:polaris service discovery cause nil panic

---

config/consumer_config.go
config/provider_config.go

feat: print logs of registered providers and consumers

---

go.mod
go.sum
metrics/prometheus/common.go
metrics/prometheus/metric_set.go
metrics/prometheus/reporter.go

refactor: use promauto and promhttp

---

common/extension/metrics_test.go
filter/metrics/filter.go
filter/metrics/filter_test.go
metrics/prometheus/after_invocation.go
metrics/prometheus/before_invocation.go
metrics/prometheus/common.go
metrics/prometheus/constant.go
metrics/prometheus/metric_set.go
metrics/prometheus/reporter.go
metrics/prometheus/reporter_test.go
metrics/reporter.go

New Metrics:
1. RequestProcessingTotal: dubbo_provider_requests_processing_total, dubbo_provider_requests_processing_total
2. RequestSucceedTotal: dubbo_provider_requests_succeed_total, dubbo_provider_requests_succeed_total

feat: add request processing total and request succeed total metrics

---

cluster/router/condition/dynamic_router.go
cluster/router/tag/match.go
cluster/router/tag/router.go
cluster/router/tag/router_test.go
config/provider_config.go
config/router_config.go
config/tracing_config.go
config/tracing_config_test.go
protocol/dubbo3/dubbo3_invoker.go
protocol/dubbo3/dubbo3_protocol.go

fix: solve config bool field zero value bug by using pointer

---

common/host_util.go
config/metric_config.go
imports/imports.go
metrics/api.go
metrics/app_info/application_info.go
metrics/common.go
metrics/common/common.go
metrics/prometheus/registry.go
metrics/reporter.go

add metrics base api interface
* add base api for collect and expose metric data
* support metric extension for more indicators
add app info metric and prometheus metric registry impl
* add metric dubbo_application_info_total

add metrics base api interface

---

common/constant/key.go
metrics/bus.go
metrics/bus_test.go
metrics/event.go
metrics/registry/event.go
metrics/registry/listener.go

A draft of the metrics bus, with examples

draft of metrics bus

---

config/metric_config.go

Enable multiple dubbo go instances, the metrics function is enabled by default and the default port of the Prometheus server is 9000, which will cause port occupation problems. It is better to turn off the metrics function by default, and leave it to the user to decide whether to enable it and enable port configuration.
---
启用多个 dubbo go 实例，metrics 功能默认开启且 Prometheus server 默认端口为9000，会产生端口占用的问题。不如默认关闭 metrics 功能，是否启用以及启用端口配置交由用户来做决定。

fix: disable metrics filter by default instead

---

go.mod
go.sum
metrics/prometheus/constant.go
metrics/prometheus/metric_set.go
metrics/prometheus/model.go
metrics/prometheus/reporter.go
metrics/util/aggregate/pane.go
metrics/util/aggregate/quantile.go
metrics/util/aggregate/quantile_test.go
metrics/util/aggregate/sliding_window.go

- Implement sliding window and wrapper it around t-digest algorithm.
- Implement rt p50, p90, p95, p99.
```
dubbo_consumer_rt_milliseconds_p50{application_name="dubbo.io",group="dubbo-go",hostname="not implemented yet",interface="org.apache.dubbogo.samples.api.Greeter",ip="192.168.48.156",method="",version="3.0.1"} 171
dubbo_consumer_rt_milliseconds_p90{application_name="dubbo.io",group="dubbo-go",hostname="not implemented yet",interface="org.apache.dubbogo.samples.api.Greeter",ip="192.168.48.156",method="",version="3.0.1"} 201.39999999999998
dubbo_consumer_rt_milliseconds_p95{application_name="dubbo.io",group="dubbo-go",hostname="not implemented yet",interface="org.apache.dubbogo.samples.api.Greeter",ip="192.168.48.156",method="",version="3.0.1"} 201.95000000000002 …
```

feat: sliding window and rt quantile metrics

---

config/metric_config.go
metadata/report/reporter_metric.go
metrics/api.go
metrics/metadata/collector.go
metrics/metadata/metric_set.go
registry/servicediscovery/service_discovery_registry.go

feat: add metadata rt metrics
> dubbo_push_rt_milliseconds_sum
dubbo_push_rt_milliseconds_last
dubbo_push_rt_milliseconds_min
dubbo_push_rt_milliseconds_max
dubbo_push_rt_milliseconds_avg
> dubbo_subscribe_rt_milliseconds_sum
dubbo_subscribe_rt_milliseconds_last
dubbo_subscribe_rt_milliseconds_min
dubbo_subscribe_rt_milliseconds_max
dubbo_subscribe_rt_milliseconds_avg
> dubbo_store_provider_interface_rt_milliseconds_avg
dubbo_store_provider_interface_rt_milliseconds_last
dubbo_store_provider_interface_rt_milliseconds_max
dubbo_store_provider_interface_rt_milliseconds_min
dubbo_store_provider_interface_rt_milliseconds_sum
> dubbo_subscribe_service_rt_milliseconds_last
dubbo_subscribe_service_rt_milliseconds_max
dubbo_subscribe_service_rt_milliseconds_min …

feat: add metadata rt metrics

---

common/host_util.go
common/host_util_test.go
metrics/api.go
metrics/prometheus/registry.go
metrics/prometheus/registry_test.go
metrics/prometheus/reporter.go
metrics/prometheus/rt_vec.go
metrics/prometheus/rt_vec_test.go
metrics/prometheus/util.go
metrics/registry/collector.go
metrics/util/aggregate/aggregator.go
metrics/util/aggregate/aggregator_test.go

1. optimize rt calculation time
The current implementation rt will be calculated every time the sample data is added, which is performance-intensive and unnecessary. 
new implementation will only be calculated when Prometheus pulls data
2. add more unit tests for metrics
3. add Rt interface to `MetricRegisrty` simplfy  rt processing
for example:
```go
var MetricRegisrty registry
registry.Rt(&MetricId{Name:"dubbo_request_rt", Desc: "Request RT"}).Observe(100)
// next time also call it in this way, no need to manually cache it
registry.Rt(&MetricId{Name:"dubbo_request_rt", Desc: "Request RT"}).Observe(100)
```
it will produce 5 metrics in prometheus:
```plain
dubbo_request_rt_avg{app="dubbo",version="1.0.0"} 45
dubbo_request_rt_last{app="dubbo",version="1.0.0"} 90 …
```

refactor: make rt metric more performance and easy to use

---

config/service_config.go

The condition of assigning a random port for protocols should be that port
is less than or equal to 0, not the length of the port string.
Fixes: #2382

fix(config): Random ports can't be assgined

---

metrics/api.go
metrics/common.go
metrics/metadata/collector.go
metrics/metadata/metric_set.go
metrics/registry/collector.go
metrics/registry/metric_set.go

migrate old RT metric impl to new RT impl , related to #2376 
1. simplify rt usage
2. fix: metric tag `application` -> `application_name`
3. fix: `dubbo_registry_notify_num_last` to metric type `gauge`

refactor: migrate old RT metric impl to new RT impl

---

common/constant/default.go
config/reference_config.go
config/service_config.go
config/service_config_test.go

refactor: simplify configuration when enable metrics

---

config/root_config.go

From the Go specification:
> "3. If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/7FQ6fOesRuY

refactor(root_config): remove redundant nil check in `Init`

---

registry/servicediscovery/service_instances_changed_listener_impl.go

refer https://github.com/apache/dubbo-go/pull/2420 last commnet

Fix：Rename 'one' to 'cacheOnce'

---

graceful_shutdown/common.go
graceful_shutdown/compat.go
graceful_shutdown/graceful_shutdown_signal_darwin.go
graceful_shutdown/graceful_shutdown_signal_linux.go
graceful_shutdown/graceful_shutdown_signal_windows.go
graceful_shutdown/options.go
graceful_shutdown/shutdown.go

In the original implementation of Graceful_Shutdown, all the processing logics exist in **RootConfig.Start()** (**gracefulShutdownInit**). As shown below:
```go
func (rc *RootConfig) Start() {
startOnce.Do(func() {
gracefulShutdownInit()
rc.Consumer.Load()
rc.Provider.Load()
exportMetadataService()
registerServiceInstance()
})
}
```
It is not convenient for just creating a **Client** because this behavior is global and embedded in **config** package.
After modularizing Graceful_Shutdown functionality, **Client** and **Server** modules could invoke **Init** and **RegisterProtocol** directly. Here is the code sample:
```go
graceful_shutdown.Init(&global.ShutdownConfig{
Timeout: "300ms"
})
// iterate protocols configured
for protocolName... {
graceful_shutdown.RegisterProtocol(protocolName) …
```

feat: modularize Graceful_Shutdown functionality

---

config/service_config.go

https://github.com/apache/dubbo-go/pull/2384 is missing a condition check, so it still cannot use random ports.
@chickenlj @AlexStocks

fix: config random port

---

config/reference_config.go
config/reference_config_test.go

This PR aims to solve this issue(https://github.com/apache/dubbo-go/issues/2439).

feat: resolve ConsumerConfig nil pointer problem

---

client/options.go
graceful_shutdown/options.go
graceful_shutdown/shutdown.go
options.go
protocol/options.go
protocol/triple/internal/client/cmd_client_with_registry/main.go
protocol/triple/internal/client/cmd_instance_with_registry/main.go
protocol/triple/internal/server/cmd_instance/main.go
protocol/triple/internal/server/cmd_instance_with_registry/main.go
protocol/triple/internal/server/cmd_server/main.go
protocol/triple/internal/server/cmd_server_with_registry/main.go
registry/options.go
server/options.go

This PR aims to solve issue(https://github.com/apache/dubbo-go/issues/2444) and unify options design.
For instance, in former implementation, we use DefaultOptions and apply those Option to DefaultOptions directly.
```go
// dubbo.WithRegistry
func WithRegistry(key string, opts ...registry.Option) ClientOption {
regOpts := registry.DefaultOptions()
for _, opt := range opts {
opt(regOpts)
}
return func(cliOpts *ClientOptions) {
if cliOpts.Registries == nil {
cliOpts.Registries = make(map[string]*global.RegistryConfig)
}
cliOpts.Registries[key] = regOpts.Registry
cliOpts.Registries[regOpts.ID] = regOpts.Registry
}
}
```
We should move this logic to registry module so that extensions would be easy to add. As a result, introducing  ```NewOptions(opts ...Option) *Options```  in each module. …

feat: simplify registry and protocol configuration

---

common/constant/key.go
config/metric_config.go
config/metric_config_test.go
metrics/config_center/collector.go
metrics/metadata/collector.go
metrics/prometheus/registry.go
metrics/registry/collector.go
metrics/rpc/collector.go

add switch for metric collector, include metadata、registry、config-center、rpc
split `PrometheusRegistry.Export` method into two method to avoid large method body

feat(metrics): add switch for metric collector

---

metrics/rpc/collector.go
metrics/rpc/metric_set.go

- implement new metrics: 
- dubbo_provider_requests_failed_total
- dubbo_consumer_requests_failed_total
- dubbo_provider_requests_failed_total_aggregate
- dubbo_consumer_requests_failed_total_aggregate
- fix a metrics naming error
According to the type of RPC exception, implement more detailed metrics to refine the granularity.

feat: add rpc exception metrics

---

.github/workflows/github-actions.yml
integrate_test.sh

We are maintaining several branches at this time, e.g. release-3.0 and
main. However, cloning dubbo-go-samples for integrate testing is still from
master. This leads to CI failure on old branch, like release-3.0, when the
master branch have received some breaking changes. Therefore, the
dubbo-go-samples' branch is required to keep same as the target branch.

ci: Clone from target branch

---

.github/workflows/github-actions.yml
integrate_test.sh

We are maintaining several branches at this time, e.g. release-3.0 and
main. However, cloning dubbo-go-samples for integrate testing is still from
master. This leads to CI failure on old branch, like release-3.0, when the
master branch have received some breaking changes. Therefore, the
dubbo-go-samples' branch is required to keep same as the target branch.

[3.0] ci: Clone from target branch

---

.github/workflows/github-actions.yml
integrate_test.sh

`$GITHUB_BASE_NAME` is an invalid variable, and is replaced with
`$GITHUB_REF_NAME` to acquire target branch of push.
Replacing mod name in `integrate_test.sh` adapts a case of
"apache/dubbo-go". It ensures that its mod name isn't changed to
"github.com/apache/dubbo-go".

ci: Fix CI testing failure on push

---

.github/workflows/github-actions.yml
integrate_test.sh

`$GITHUB_BASE_NAME` is an invalid variable, and is replaced with
`$GITHUB_REF_NAME` to acquire target branch of push.
Replacing mod name in `integrate_test.sh` adapts a case of
"apache/dubbo-go". It ensures that its mod name isn't changed to
"github.com/apache/dubbo-go".

[3.0] ci: Fix CI testing failure on push

---

protocol/jsonrpc/server.go

This patch limits the max size of header to 8Mib to avoid OOM issues.

[3.0] fix(jsonrpc): Limit header size to avoid unexpected OOM

---

protocol/jsonrpc/server.go

This patch limits the max size of header to 8Mib to avoid OOM issues.

fix(jsonrpc): Limit header size to avoid unexpected OOM

---

config/metric_config.go
config/metric_config_test.go

refactor: metrics config

---

client/action.go
client/options_test.go
dubbo.go
protocol/triple/internal/client/cmd_client/main.go
protocol/triple/internal/client/cmd_instance/main.go

This PR aims to support another type of configuring ```client.WithURL```:
```go
client.WithURL("127.0.0.1:20000")
client.WithURL("tri://127.0.0.1:20000")
```
Both of them could work well.

feat: support configuring client.WithURL without protocol prefix

---

protocol/triple/triple_test.go

This PR aims to fix ```TestInvoke``` in /protocol/triple/triple_test.go.

fix: add Interface to mock URL for fixing TestInvoke

---

client/options.go

Registries can be set at client and reference level, check and set client level registry if reference level is empty.

Check and set client level registry if reference level is empty.

---

config/application_config.go
metadata/service/exporter/configurable/exporter.go
version.go

https://github.com/apache/dubbo-go/issues/2537

fix: metadata port reuse

---

cluster/router/condition/dynamic_router.go
cluster/router/tag/router.go

related #2558
I think if users don't set config center ,we should print a info log rather than a warning, telling the user that the router will not be enabled

Fix:modify router warn log

---

cluster/router/condition/dynamic_router.go
cluster/router/tag/router.go

fix:merge #2559 into main branch

---

imports/imports.go

Fix the following issues.
```
2024-01-15 19:16:27     INFO    logger/logging.go:42    The following profiles are active: [default]
2024-01-15 19:16:27     INFO    config/root_config.go:138       [Config Center] Config center doesn't start
panic: Cannot find the trace provider with name otlp-grpc
```

Fix: init otel-grpc exporter

---

registry/directory/directory.go

refer #2430
In the case that a large number of services go offline in a short period of time, the dubbo service will call the offline service
This is a temporary solution, we will later reproduce the scenario and test its performance

fix:call offline services

---

metadata/report/nacos/report.go
metadata/report/nacos/report_test.go

[3.1] Fix nacos App Metadata not compatible with java

---

dubbo.go
dubbo_test.go
global/application_config.go
global/config_center_config.go
global/config_test.go
global/consumer_config.go
global/custom_config.go
global/logger_config.go
global/metadata_report_config.go
global/method_config.go
global/metric_config.go
global/otel_config.go
global/profiles_config.go
global/protocol_config.go
global/provider_config.go
global/reference_config.go
global/registry_config.go
global/service_config.go
global/shutdown_config.go
global/tls_config.go
options.go

feat: deep copy the configuration when instanceOptions flow to ServerOptions/ClientOptions

---

metadata/report/nacos/report.go
metadata/report/nacos/report_test.go

Backport nacos App Metadata not compatible with java (#2563)
Fix#2543

Backport to main branch: nacos App Metadata not compatible with java (#2563)

---

compat.go
options.go

fix: unable to merge configurations from the config_center

---

protocol/triple/triple_protocol/triple_ext_test.go

fix : fix test case

---

common/metadata_info.go
metadata/service/local/metadata_service_proxy_factory.go
registry/servicediscovery/service_discovery_registry.go
registry/servicediscovery/service_instances_changed_listener_impl.go

fix #2650
fix Panic caused by failure to connect to the peer when obtaining remote metadata
The callback function of the registration center will not be interrupted when an error occurs in obtaining remote metadata.

fix Panic caused by failure to connect to the peer when obtaining remote metadata

---

otel/trace/otlp/exporter.go

backport #2666 to 3.1
Co-authored-by: yunfei <qiuyunfei@kiwiing.com>
(cherry picked from commit 1bd6abc9110f07daec24ec0c09dac9c987e20593)

Fix:Initialize the correct otel-grpc exporter (#2666)

---

cluster/router/condition/dynamic_router.go
cluster/router/condition/route.go
cluster/router/condition/router_test.go
cluster/utils/version.go
common/constant/key.go
common/constant/version.go
config/router_config.go

to support #2684 
new condition-rule config like this
```yaml
configVersion: v3.1
scope: service
force: true
runtime: true
enabled: true
key: org.apache.dubbo.samples.CommentService
conditions:
- rule: method=getComment & env=gray & region=beijing => region=beijing & env=gray
force: fasle
priority: 10
- rule: method=getComment => region=Hangzhou
force: false
priority: 10
- rule: method=echo =>
force: true
priority: 15
```
| Condition Field | Type   | Required | DefaultValue |
|-----------------|--------|---------|---------|
| Rule            | String |   &#10003;    |         |
| Force           | Bool   |         | False   |
| Priority        | Int64  |         | 0       |
through `configVersion` to choose parse and load logic. 
set `configVersion: v3.1` to use new feature.

support conditional routing with multiple destinations, customize conditional routing priorities and operation in route fail

---

cluster/router/condition/dynamic_router.go
cluster/router/condition/route.go
cluster/router/condition/router_test.go
common/constant/key.go
config/router_config.go

>   to support #2684 
This doc show how to set up condition-router configurations for your services/application. 
The configurations are defined in a YAML format and must adhere to specific rules and parameters to ensure proper functioning.
```yaml
configVersion: v3.1 # be v3.1 or V3.1 to use this
scope: service      # must be 'service' or 'application'
key: org.apache.dubbo.samples.CommentService # [service name] or [application name]
force: false        # decide hole condition route an empty set, return err Or ignore this rule
runtime: true       # decide is use cache
enabled: true       # decide is the rule enabled 
conditions:         # contains by many conditions, sort by condition.priority
- priority: 10    # default 0, expect > 0
from:           # match consumer-side url, match …
```

Design and implement new conditional rules V3.1

---

config/registry_config.go
global/registry_config.go
registry/options.go

- Fix unable to set UseAsMetaReport and UseAsConfigCenter as `false` by fluent API or YAML Config

Update UseAsMetaReport and UseAsConfigCenter as String to prevent value override

---

registry/nacos/service_discovery.go
registry/servicediscovery/service_discovery_registry.go
registry/servicediscovery/service_instances_changed_listener_impl.go

1. fix wrong service name `DEFAULT_GROUP@@app_name` issue, happens when client starts before provider registers `mapping`
2. fix service discovery issue  when an interface is exported by different apps.

Fix nacos service discovery issue

---

cluster/router/condition/dynamic_router.go
cluster/router/condition/factory.go
cluster/router/tag/factory.go
cluster/router/tag/router.go
protocol/triple/triple_invoker.go
protocol/triple/triple_protocol/client.go

If the router rule is empty, a parsing error occurs.

Fix router rule parsing log error

---

common/url.go
protocol/dubbo/dubbo_exporter.go
protocol/dubbo/dubbo_invoker.go
protocol/dubbo3/dubbo3_exporter.go
protocol/grpc/grpc_exporter.go
protocol/invoker.go
protocol/jsonrpc/jsonrpc_exporter.go
protocol/rest/rest_exporter.go
protocol/triple/triple_exporter.go

Bssed on PR #2223 ,the main purpose of this PR is to fix the memory leak problem caused by the url pointer in baseinvoker not being released correctly. You can refer to the following issue：
FIXES: #2701 #2339 #2031

fix: set baseinvoker's url to nil to address memory leak issues

---

proxy/proxy_factory/pass_through.go

The intention here should be to initialize a slice with a capacity of 5 rather than initializing the length of this slice.

fix: fix slice init length

---

cluster/router/affinity/router.go

Modify the affinity log to avoid misunderstandings

---

config/provider_config.go
config/service_config.go
config/service_config_test.go

fix typos:
`serivce`->`service`
`balancce` -> `balance`
skip changelog

Fix typos: serivce->service, balancce->balance

---

protocol/triple/internal/client/common/client.go

Here  `sendErr` should be returned instead of `err`.

fix: Fix problematic error returns

---

protocol/dubbo/hessian2/hessian_dubbo.go
protocol/dubbo/impl/response.go
protocol/dubbo3/dubbo3_exporter.go
protocol/grpc/internal/routeguide/client.go
protocol/jsonrpc/jsonrpc_exporter.go
protocol/rest/rest_exporter.go
registry/etcdv3/service_discovery.go
xds/credentials/certgenerate/generate_cert.go

Fix some comments
The new pr for https://github.com/apache/dubbo-go/pull/2305

chore: fix some comments

---

config/reference_config.go
go.mod
go.sum

There is a memory leak when using the dubbo-go-hessian2 protocol(https://github.com/apache/dubbo-go/issues/2683). Since the dubbo-go-hessian2 already fixed in (https://github.com/apache/dubbo-go-hessian2/pull/374) and released a new version with tag v1.12.5. So update the version in dubbo-go.

fix issue 2683: defeat memory leak

---

registry/nacos/listener.go
registry/nacos/registry.go

- Support subscribing to multiple categories when subscribing to Nacos, not just providers
- fix the use of handleServiceEvents causes blocking in handling service events.
- Optimize Nacos subscription logic

nacos registry support subscribe multi category

---

config/root_config.go
registry/protocol/protocol.go

fix：https://github.com/apache/dubbo-go/issues/2094 Multi registry Address verification 
Rewriting with LoadOrStore here can avoid the problem of duplicate creation under multi-threaded concurrency.

Multi registry verification and Use LoadOrStore instead

---

common/extension/filter.go
common/extension/loadbalance.go
common/extension/memory_leak_test.go
common/extension/protocol.go
filter/accesslog/filter.go
filter/accesslog/filter_test.go
filter/accesslog/memory_leak_test.go
registry/nacos/service_discovery.go
registry/nacos/service_discovery_test.go

This PR addresses critical memory leaks, goroutine deadlocks, and file handle leaks that could lead to resource exhaustion in production environments. The fixes include comprehensive architectural improvements to the access log filter, extension cache management, and Nacos service discovery components.
Key Changes
Access Log Filter Refactoring (filter/accesslog/)
- Fix goroutine deadlock: Move context management to Filter struct to reduce global dependencies
- Add timeout protection: Implement timeout mechanisms for writeLogToFile to prevent deadlocks
- Improve architecture: Extract goroutine logic to dedicated start/processLogs/drainLogs methods
- Enhanced error handling: Add panic recovery in processLogs goroutine
- Clean up globals: Remove unused global variables (shutdownOnce, …

fix: resolve memory leaks in goroutine management, file handles, and extension caches
